# M12U: Confident About What?

This chapter draws on material from [Introduction: #TravelingWhileTrans, Design Justice, and Escape from the Matrix of Domination](https://designjustice.mitpress.mit.edu/pub/ap8rgw5e/release/1), by [Sasha Costanza-Chock](https://www.schock.cc/), licensed under CC BY 4.0

Changes to the source material include adding new material, (rarely) deleting original material, changing the citation style, and adding first-person introductory and concluding language from current author.

## Introduction

As we'll see in this week's walkthrough, confidence intervals are really important! On one hand, they're an important recognition that even with the best applications of statistical analysis, we never have a perfect answer to the questions that we're asking. However, they also let us skip the step of throwing our hands up in despair about the impossibility of knowing and give us a practical workaround: We may not know the exact answer, but we have a certain level of confidence that the answer falls within a given range.

As we'll see in future weeks, this kind of reasoning is really helpful in inferential statistics. Sure, we can't answer whether a given measurement is the "correct" value, but we can use the basic ideas behind confidence intervals to shift our attention to a different question: *What values are unlikely to be "correct"?* In other words, values outside of a confidence interval are unlikely to correspond with a given true value for a particular measurement, and knowing that can be a lot more helpful.

I'm being a bit ambiguous here: We need to read more about confidence intervals this week and lay some more conceptual groundwork next week before we really see how confidence intervals support inferential statistics. However, the basic idea ought to be clear by the end of this week: The more confident we are that a value ought to fall within a certain range, the more suspicious that we ought to be of values that fall outside of that range.

That said, even though this kind of reasoning comes with a certain amount of statistical humility, it promotes an idea of *normativity.* That is, that certain values of a particular variable are *normal*, and other values are *abnormal*, and we ought to be suspicious of abnormal values. Let's be clear—sometimes, this reasoning is appropriate and helpful! I'm really glad that my physician can make distinctions between when my heart is behaving normally and when it's behaving abnormally—and I'm glad that she raises suspicion when it's behaving abnormally.

However, there are also times that our confidence in the normality of certain things (and the suspicious abnormality of other things) is misplaced. Overconfidence in what is normal and what isn't can lead to discrimination against and even persecution of people who don't fit a particular image of normality, and that's not a good thing.

The bulk of this reading is going to include a story along these lines that I've taken from Dr. Sasha Costanza-Chock's book *Design Justice*, as I've indicated above. Previously in the semester, when I've adapted a reading from another source, I've taken advantage of the permissive license applied to the source to add my own voice to it, edit the original language, etc.

However, this is a highly personal story from Dr. Costanza-Chock, and it would be wildly inappropriate for me to take that same approach here. In a few cases, I have removed language that makes reference to later chapters in her book (because that could be confusing here), I have changed the citation style to fit with the rest of our readings, and I have broken up one paragraph that got overly long after making changes to citation style. Other than that, though, I have kept Dr. Costanza-Chock's original language intact, and all first-person pronouns refer to her, not me. 

> To make this more clear, I have used "blockquote formatting" (like this paragraph) to represent her language.

As you read the story, consider how statistics, confidence, and normativity play a role in making travel by plane more difficult for some people than others. As with previous readings, this isn't an argument for throwing out confidence intervals and the rest of data science—rather, this is another reminder of how important it is that we be mindful and careful in the ways that we apply data science in the world.

## #TravelingWhileTrans

> It’s June 2017, and I’m standing in the security line at the Detroit Metro Airport. I’m on my way back to Boston from the Allied Media Conference (AMC), a “collaborative laboratory of media-based organizing” that’s been held every year in Detroit for the past two decades (see alliedmedia.org). At the AMC, over two thousand people—media makers, designers, activists and organizers, software developers, artists, filmmakers, researchers, and all kinds of cultural workers—gather each June to share ideas and strategies for how to create a more just, creative, and collaborative world. As a nonbinary, trans\*, femme-presenting person, my time at the AMC was deeply liberating (For a recent discussion of the increasingly widespread use of the term trans\* with an asterisk, see Halberstam [2018]). It’s a conference that strives harder than any that I know of to be inclusive of all kinds of people, including queer, trans\*, intersex, and gender-non-conforming (QTI/GNC) folks. Although it’s far from perfect, and every year inevitably brings new challenges and difficult conversations about what it means to construct a truly inclusive space, it’s a powerful experience. Emerging from nearly a week immersed in this parallel world, I’m tired, but on a deep level, refreshed; my reservoir of belief in the possibility of creating better futures has been replenished.

> I will certainly be spared the most disruptive and harmful possible outcomes of security screening. For example, I don’t have to worry that this process will lead to my being placed in a detention center or in deportation proceedings; I won’t be hooded and whisked away to Guantanamo Bay or to one of the many other secret prisons that form part of the global infrastructure of the so-called war on terror (Sadat, 2005); most likely, I won’t even miss my flight while detained for what security expert Bruce Schneier (2006) describes as “security theater.” Only once in all of my travels have I been taken aside, placed into a waiting room, and subjected to additional questioning by the Department of Homeland Security (DHS). Despite my participation in social movement networks, including the global justice movement, Indymedia, the immigrant rights movement, countersurveillance work, and more, my white skin, institutional affiliations, educational background, and US citizenship have largely protected me from the most egregious types of abuse by state power.

> On the other hand, my heartbeat speeds up slightly as I near the end of the line, because I know that I’m almost certainly about to experience an embarrassing, uncomfortable, and perhaps humiliating search by a Transportation Security Administration (TSA) officer, after my body is flagged as anomalous by the millimeter wave scanner. I know that this is almost certainly about to happen because of the particular sociotechnical configuration of gender normativity (*cis-normativity*, or the assumption that all people have a gender identity that is consistent with the sex they were assigned at birth) that has been built into the scanner, through the combination of user interface (UI) design, scanning technology, binary-gendered body-shape data constructs, and risk detection algorithms, as well as the socialization, training, and experience of the TSA agents (Costello, 2016).

> TSA agent motions me to step into the millimeter wave scanner. I raise my arms and place my hands in a triangle shape, palms facing forward, above my head. The scanner spins around my body, and then the agent signals for me to step forward out of the machine and wait with my feet on the pad just past the scanner exit. I glance to the left, where a screen displays an abstracted outline of a human body. As I expected, bright fluorescent yellow pixels on the flat-panel display highlight my groin area. You see, when I entered the scanner, the TSA operator on the other side was prompted by the UI to select Male or Female; the button for Male is blue, the button for Female is pink. Since my gender presentation is nonbinary femme, usually the operator selects Female. However, the three-dimensional contours of my body, at millimeter resolution, differ from the statistical norm of female bodies as understood by the data set and risk algorithm designed by the manufacturer of the millimeter wave scanner (and its subcontractors), and as trained by a small army of clickworkers tasked with labeling and classification (as scholars Lilly Irani [2016], Nick Dyer-Witheford [2016], Mary Gray and Siddharth Suri [2019], among others, remind us). If the agent selects Male, my breasts are large enough, statistically speaking, in comparison to the normative male body-shape construct in the database, to trigger an anomaly warning and a highlight around my chest area. If they select Female, my groin area deviates enough from the statistical female norm to trigger the risk alert. In other words, I can’t win. This sociotechnical system is sure to mark me as "risky," and that will trigger an escalation to the next level in the TSA security protocol."

> This is, in fact, what happens: I’ve been flagged. The screen shows a fluorescent yellow highlight around my groin. Next, the agent asks me to step aside, and (as usual) asks for my consent to a physical body search. Typically, once I’m close enough, the agent becomes confused about my gender. This presents a problem, because the next fork in the security protocol is for either a male or female TSA agent to conduct a body search by running their hands across my arms and armpits, chest, hips and legs, and inner thighs. According to TSA policy, “if a pat-down is performed, it will be conducted by an officer of the same gender as you present yourself” (see https://www.tsa.gov/transgender-passengers). Sometimes, the agent will assume I prefer to be searched by a female agent; sometimes, a male. Occasionally, they ask for my preference. Unfortunately, “neither” is an honest but unacceptable response. Today, I’m particularly unlucky: a nearby male-presenting agent, observing the interaction, loudly states “I’ll do it!” and strides over to me. I say, “Aren’t you going to ask me what I prefer?” He pauses, then begins to move toward me again, but the female-presenting agent who is operating the scanner stops him. She asks me what I prefer. Now I’m standing in public, flanked by two TSA agents, with a line of curious travelers watching the whole interaction. Ultimately, the male-presenting agent backs off and the female-presenting agent searches me, making a face as if she’s as uncomfortable as I am, and I’m cleared to continue on to my gate.

> The point of this story is to provide a small but concrete example from my own daily lived experience of how larger systems—including norms, values, and assumptions—are encoded in and reproduced through the design of sociotechnical systems, or in political theorist Langdon Winner’s (1980) famous words, how “artifacts have politics." In this case, cis-normativity is enforced at multiple levels of a traveler’s interaction with airport security systems. The database, models, and algorithms that assess deviance and risk are all binary and cis-normative. The male/female gender selector UI is binary and cis-normative. As Anna Lauren Hoffmann [notes](https://twitter.com/annaeveryday/status/1036635912761819136) about the simplified gender binary interface, “The thing that really gets me is that this screen was developed as a privacy-preserving compromise after folks realized the level of detail these machines were *actually* capable of rendering!”

> The assignment of a male or female TSA agent to perform the additional, more invasive search is cis-normative and binary-gender normative as well. At each stage of this interaction, airport security technology, databases, algorithms, risk assessment, and practices are all designed based on the assumption that there are only two genders, and that gender presentation will conform with so-called biological sex. Anyone whose body doesn’t fall within an acceptable range of “deviance” from a normative binary body type is flagged as risky and subjected to a heightened and disproportionate burden of the harms (both small and, potentially, large) of airport security systems and the violence of empire they instantiate. QTI/GNC people are thus disproportionately burdened by the design of millimeter wave scanning technology and the way that technology is used. The system is biased against us. Most cisgender people are unaware of the fact that the millimeter wave scanners operate according to a binary and cis-normative gender construct; most trans\* people know, because it directly affects our lives. In 2009, Toby Beauchamp wrote about state surveillance and trans\* concealment/visibility. In September of 2016, Shadi Petosky brought national attention to the challenges of #TravelingWhileTrans when she live-tweeted her experience with an invasive search by TSA agents at the Orlando airport, after she was flagged in a millimeter wave scan for presenting as female while having a penis (see Lee, 2016).

> These systems are biased against QTI/GNC people, as I’ve described; against Black women, who frequently experience invasive searches of their hair, as [documented](https://www.propublica.org/article/tsa-not-discriminating-against-black-women-but-their-body-scanners-might-be) by the team of investigative journalists at ProPublica; and against Sikh men, Muslim women, and others who wear headwraps, as described by sociologist Simone Browne (2015) in her brilliant book *Dark Matters*. As Browne discusses, and as Joy Buolamwini (2017), founder of the Algorithmic Justice League, technically demonstrates, gender itself is racialized: humans have trained our machines to categorize faces and bodies as male and female through lenses tinted by the optics of white supremacy. Airport security is also systematically biased against Disabled people, who are more likely to be flagged as risky if they have non-normative body shapes and/or use prostheses, as well as anyone who uses a wearable or implanted medical device. Those who are simultaneously QTI/GNC, Black, Indigenous, people of color (PoC), Muslim, Sikh, immigrant, and/or Disabled are doubly, triply, or multiply burdened by, and face the highest risk of harms from, this system.

> I first publicly shared this experience in an essay for the *Journal of Design and Science* that I wrote in response to the “Resisting Reduction” manifesto (Ito, 2017), a timely call for thoughtful conversation about the limits and possibilities of artificial intelligence (AI). That call resonated very deeply with me because as a nonbinary trans\* feminine person, I walk through a world that has in many ways been designed to deny the possibility of my existence. The same cisnormative, racist, and ableist approach that is used to train the models of the millimeter wave scanners is now being used to develop AI in nearly every domain. From my standpoint, I worry that the current path of AI development will reproduce systems that erase those of us on the margins, whether intentionally or not, through the mundane and relentless repetition of reductive norms in a thousand daily interactions with AI systems that, increasingly, weave the very fabric of our lives.

## Conclusion

Not all of the normativity described by Dr. Costanza-Chock in this story is a result of data science and confidence intervals, but data science and confidence intervals nearly always contribute to our ideas of what is normal and what is suspiciously abnormal. We cannot allow ourselves to use data science in a way that makes some people normal and other people suspiciously abnormal—and yet, as Dr. Costanza-Chock suggests, this is something that is already happening. As you continue working with data science in this class and in other spaces, think carefully about what you're placing confidence in and whether that is warranted!

## References

Beauchamp, T. (2009). Artful concealment and strategic visibility: Transgender bodies and U.S. state surveillance after 9/11. *Surveillance & Society*, *6*(4), 356–366.

Browne, S. (2015). *Dark matters: On the surveillance of Blackness*. Duke University Press.

Costello, C. G. (2016, January 3). Traveling while trans: The false promise of better treatment. *Trans Advocate*. http://transadvocate.com/the-tsa-a-binary-body-system-in-practice_n_15540.htm.

Halberstam, J. (2018). *Trans\*: A Quick and Quirky Account of Gender Variability*. Oakland: University of California Press.

Ito, J. (2017). Resisting reduction: A manifesto. *Journal of Design and Science*. https://jods.mitpress.mit.edu/pub/resisting-reduction.

Lee, J. (2016, February 3). Alarming TSA. *The Fourth Wave*. https://thefourthwavepitt.com/2016/02/03/alarming-tsa.

Sadat, L. N. (2005). Ghost prisoners and black sites: Extraordinary rendition under international law. *Case Western Reserve Journal of International Law*, *37*, 309–342.

Schneier, B. (2006). *Beyond fear: Thinking sensibly about security in an uncertain world*. Springer Science & Business Media.

Winner, L. (1980). Do artifacts have politics? *Daedalus* *109*(1), 121–136.