<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>22 Data Visualization | Introduction to Data Science</title>
  <meta name="description" content="22 Data Visualization | Introduction to Data Science" />
  <meta name="generator" content="bookdown 0.29 and GitBook 2.6.7" />

  <meta property="og:title" content="22 Data Visualization | Introduction to Data Science" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="22 Data Visualization | Introduction to Data Science" />
  
  
  

<meta name="author" content="Spencer P. Greenhalgh, PhD" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="viz.html"/>
<link rel="next" href="m7c-practice-visualizing-your-own-data.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a></li>
<li class="chapter" data-level="2" data-path="module-1-understanding.html"><a href="module-1-understanding.html"><i class="fa fa-check"></i><b>2</b> Module 1 Understanding</a></li>
<li class="chapter" data-level="3" data-path="m1a-install-r-and-rstudio.html"><a href="m1a-install-r-and-rstudio.html"><i class="fa fa-check"></i><b>3</b> M1A: Install R and RStudio</a>
<ul>
<li class="chapter" data-level="3.1" data-path="m1a-install-r-and-rstudio.html"><a href="m1a-install-r-and-rstudio.html#introduction-1"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="m1a-install-r-and-rstudio.html"><a href="m1a-install-r-and-rstudio.html#r"><i class="fa fa-check"></i><b>3.2</b> R</a></li>
<li class="chapter" data-level="3.3" data-path="m1a-install-r-and-rstudio.html"><a href="m1a-install-r-and-rstudio.html#rstudio"><i class="fa fa-check"></i><b>3.3</b> RStudio</a></li>
<li class="chapter" data-level="3.4" data-path="m1a-install-r-and-rstudio.html"><a href="m1a-install-r-and-rstudio.html#references"><i class="fa fa-check"></i><b>3.4</b> References</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="m1c-introduce-yourself-to-the-class.html"><a href="m1c-introduce-yourself-to-the-class.html"><i class="fa fa-check"></i><b>4</b> M1C: Introduce Yourself to the Class</a></li>
<li class="chapter" data-level="5" data-path="m2u-the-new-and-shiny-science-of-data.html"><a href="m2u-the-new-and-shiny-science-of-data.html"><i class="fa fa-check"></i><b>5</b> M2U: The New(?) and Shiny(?) Science of Data</a>
<ul>
<li class="chapter" data-level="5.1" data-path="m2u-the-new-and-shiny-science-of-data.html"><a href="m2u-the-new-and-shiny-science-of-data.html#data-data-science-and-big-data"><i class="fa fa-check"></i><b>5.1</b> Data, Data Science, and Big Data</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="m2u-the-new-and-shiny-science-of-data.html"><a href="m2u-the-new-and-shiny-science-of-data.html#data"><i class="fa fa-check"></i><b>5.1.1</b> Data</a></li>
<li class="chapter" data-level="5.1.2" data-path="m2u-the-new-and-shiny-science-of-data.html"><a href="m2u-the-new-and-shiny-science-of-data.html#data-science"><i class="fa fa-check"></i><b>5.1.2</b> Data Science</a></li>
<li class="chapter" data-level="5.1.3" data-path="m2u-the-new-and-shiny-science-of-data.html"><a href="m2u-the-new-and-shiny-science-of-data.html#big-data"><i class="fa fa-check"></i><b>5.1.3</b> Big Data</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="m2u-the-new-and-shiny-science-of-data.html"><a href="m2u-the-new-and-shiny-science-of-data.html#the-many-skills-of-data-science"><i class="fa fa-check"></i><b>5.2</b> The Many Skills of Data Science</a></li>
<li class="chapter" data-level="5.3" data-path="m2u-the-new-and-shiny-science-of-data.html"><a href="m2u-the-new-and-shiny-science-of-data.html#references-1"><i class="fa fa-check"></i><b>5.3</b> References</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="getting-started.html"><a href="getting-started.html"><i class="fa fa-check"></i><b>6</b> M2A: Getting Started with Data in R</a>
<ul>
<li class="chapter" data-level="6.1" data-path="getting-started.html"><a href="getting-started.html#introduction-2"><i class="fa fa-check"></i><b>6.1</b> Introduction</a></li>
<li class="chapter" data-level="6.2" data-path="getting-started.html"><a href="getting-started.html#r-rstudio"><i class="fa fa-check"></i><b>6.2</b> What are R and RStudio?</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="getting-started.html"><a href="getting-started.html#using-r-via-rstudio"><i class="fa fa-check"></i><b>6.2.1</b> Using R via RStudio</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="getting-started.html"><a href="getting-started.html#code"><i class="fa fa-check"></i><b>6.3</b> How do I code in R?</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="getting-started.html"><a href="getting-started.html#programming-concepts"><i class="fa fa-check"></i><b>6.3.1</b> Basic programming concepts and terminology</a></li>
<li class="chapter" data-level="6.3.2" data-path="getting-started.html"><a href="getting-started.html#messages"><i class="fa fa-check"></i><b>6.3.2</b> Errors, warnings, and messages</a></li>
<li class="chapter" data-level="6.3.3" data-path="getting-started.html"><a href="getting-started.html#tips-code"><i class="fa fa-check"></i><b>6.3.3</b> Tips on learning to code</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="getting-started.html"><a href="getting-started.html#packages"><i class="fa fa-check"></i><b>6.4</b> What are R packages?</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="getting-started.html"><a href="getting-started.html#package-installation"><i class="fa fa-check"></i><b>6.4.1</b> Package installation</a></li>
<li class="chapter" data-level="6.4.2" data-path="getting-started.html"><a href="getting-started.html#package-loading"><i class="fa fa-check"></i><b>6.4.2</b> Package loading</a></li>
<li class="chapter" data-level="6.4.3" data-path="getting-started.html"><a href="getting-started.html#package-use"><i class="fa fa-check"></i><b>6.4.3</b> Package use</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="getting-started.html"><a href="getting-started.html#nycflights13"><i class="fa fa-check"></i><b>6.5</b> Explore your first datasets</a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="getting-started.html"><a href="getting-started.html#nycflights13-package"><i class="fa fa-check"></i><b>6.5.1</b> <code>nycflights13</code> package</a></li>
<li class="chapter" data-level="6.5.2" data-path="getting-started.html"><a href="getting-started.html#flights-data-frame"><i class="fa fa-check"></i><b>6.5.2</b> <code>flights</code> data frame</a></li>
<li class="chapter" data-level="6.5.3" data-path="getting-started.html"><a href="getting-started.html#exploredataframes"><i class="fa fa-check"></i><b>6.5.3</b> Exploring data frames</a></li>
<li class="chapter" data-level="6.5.4" data-path="getting-started.html"><a href="getting-started.html#identification-vs-measurement-variables"><i class="fa fa-check"></i><b>6.5.4</b> Identification and measurement variables</a></li>
<li class="chapter" data-level="6.5.5" data-path="getting-started.html"><a href="getting-started.html#help-files"><i class="fa fa-check"></i><b>6.5.5</b> Help files</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="getting-started.html"><a href="getting-started.html#conclusion"><i class="fa fa-check"></i><b>6.6</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="m2c-set-up-github.html"><a href="m2c-set-up-github.html"><i class="fa fa-check"></i><b>7</b> M2C: Set up GitHub</a>
<ul>
<li class="chapter" data-level="7.1" data-path="m2c-set-up-github.html"><a href="m2c-set-up-github.html#introduction-3"><i class="fa fa-check"></i><b>7.1</b> Introduction</a></li>
<li class="chapter" data-level="7.2" data-path="m2c-set-up-github.html"><a href="m2c-set-up-github.html#gitand-githubin-data-science"><i class="fa fa-check"></i><b>7.2</b> Git—and GitHub—in Data Science</a></li>
<li class="chapter" data-level="7.3" data-path="m2c-set-up-github.html"><a href="m2c-set-up-github.html#github-in-ictlis-661"><i class="fa fa-check"></i><b>7.3</b> GitHub in ICT/LIS 661</a></li>
<li class="chapter" data-level="7.4" data-path="m2c-set-up-github.html"><a href="m2c-set-up-github.html#setting-up-github"><i class="fa fa-check"></i><b>7.4</b> Setting Up GitHub</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="m2c-set-up-github.html"><a href="m2c-set-up-github.html#creating-a-github-account"><i class="fa fa-check"></i><b>7.4.1</b> Creating a GitHub Account</a></li>
<li class="chapter" data-level="7.4.2" data-path="m2c-set-up-github.html"><a href="m2c-set-up-github.html#setting-up-a-github-repository-for-class"><i class="fa fa-check"></i><b>7.4.2</b> Setting up a GitHub Repository for Class</a></li>
<li class="chapter" data-level="7.4.3" data-path="m2c-set-up-github.html"><a href="m2c-set-up-github.html#installing-github-desktop"><i class="fa fa-check"></i><b>7.4.3</b> Installing GitHub Desktop</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="m2c-set-up-github.html"><a href="m2c-set-up-github.html#moving-forward"><i class="fa fa-check"></i><b>7.5</b> Moving Forward</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="m3u-research-paradigms-and-reproducibility.html"><a href="m3u-research-paradigms-and-reproducibility.html"><i class="fa fa-check"></i><b>8</b> M3U: Research Paradigms and Reproducibility</a>
<ul>
<li class="chapter" data-level="8.1" data-path="m3u-research-paradigms-and-reproducibility.html"><a href="m3u-research-paradigms-and-reproducibility.html#introduction-4"><i class="fa fa-check"></i><b>8.1</b> Introduction</a></li>
<li class="chapter" data-level="8.2" data-path="m3u-research-paradigms-and-reproducibility.html"><a href="m3u-research-paradigms-and-reproducibility.html#reproducibility-and-paradigms"><i class="fa fa-check"></i><b>8.2</b> Reproducibility and Paradigms</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="m3u-research-paradigms-and-reproducibility.html"><a href="m3u-research-paradigms-and-reproducibility.html#an-example-paradigm"><i class="fa fa-check"></i><b>8.2.1</b> An Example Paradigm</a></li>
<li class="chapter" data-level="8.2.2" data-path="m3u-research-paradigms-and-reproducibility.html"><a href="m3u-research-paradigms-and-reproducibility.html#another-example-paradigm"><i class="fa fa-check"></i><b>8.2.2</b> Another Example Paradigm</a></li>
<li class="chapter" data-level="8.2.3" data-path="m3u-research-paradigms-and-reproducibility.html"><a href="m3u-research-paradigms-and-reproducibility.html#why-do-paradigms-matter"><i class="fa fa-check"></i><b>8.2.3</b> Why Do Paradigms Matter?</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="m3u-research-paradigms-and-reproducibility.html"><a href="m3u-research-paradigms-and-reproducibility.html#supporting-reproducibility"><i class="fa fa-check"></i><b>8.3</b> Supporting Reproducibility</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="m3u-research-paradigms-and-reproducibility.html"><a href="m3u-research-paradigms-and-reproducibility.html#open-design"><i class="fa fa-check"></i><b>8.3.1</b> Open Design</a></li>
<li class="chapter" data-level="8.3.2" data-path="m3u-research-paradigms-and-reproducibility.html"><a href="m3u-research-paradigms-and-reproducibility.html#open-analysis"><i class="fa fa-check"></i><b>8.3.2</b> Open Analysis</a></li>
<li class="chapter" data-level="8.3.3" data-path="m3u-research-paradigms-and-reproducibility.html"><a href="m3u-research-paradigms-and-reproducibility.html#open-publication"><i class="fa fa-check"></i><b>8.3.3</b> Open Publication</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="m3u-research-paradigms-and-reproducibility.html"><a href="m3u-research-paradigms-and-reproducibility.html#conclusion-1"><i class="fa fa-check"></i><b>8.4</b> Conclusion</a></li>
<li class="chapter" data-level="8.5" data-path="m3u-research-paradigms-and-reproducibility.html"><a href="m3u-research-paradigms-and-reproducibility.html#references-2"><i class="fa fa-check"></i><b>8.5</b> References</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="m3a-using-projects-and-scripts-in-r.html"><a href="m3a-using-projects-and-scripts-in-r.html"><i class="fa fa-check"></i><b>9</b> M3A: Using Projects and Scripts in R</a>
<ul>
<li class="chapter" data-level="9.1" data-path="m3a-using-projects-and-scripts-in-r.html"><a href="m3a-using-projects-and-scripts-in-r.html#introduction-5"><i class="fa fa-check"></i><b>9.1</b> Introduction</a></li>
<li class="chapter" data-level="9.2" data-path="m3a-using-projects-and-scripts-in-r.html"><a href="m3a-using-projects-and-scripts-in-r.html#more-about-r-and-rstudio"><i class="fa fa-check"></i><b>9.2</b> More About R and RStudio</a></li>
<li class="chapter" data-level="9.3" data-path="m3a-using-projects-and-scripts-in-r.html"><a href="m3a-using-projects-and-scripts-in-r.html#the-console-and-the-workspace"><i class="fa fa-check"></i><b>9.3</b> The Console and the Workspace</a></li>
<li class="chapter" data-level="9.4" data-path="m3a-using-projects-and-scripts-in-r.html"><a href="m3a-using-projects-and-scripts-in-r.html#holding-onto-code"><i class="fa fa-check"></i><b>9.4</b> Holding Onto Code</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="m3a-using-projects-and-scripts-in-r.html"><a href="m3a-using-projects-and-scripts-in-r.html#rstudio-projects"><i class="fa fa-check"></i><b>9.4.1</b> RStudio Projects</a></li>
<li class="chapter" data-level="9.4.2" data-path="m3a-using-projects-and-scripts-in-r.html"><a href="m3a-using-projects-and-scripts-in-r.html#using-scripts"><i class="fa fa-check"></i><b>9.4.2</b> Using Scripts</a></li>
<li class="chapter" data-level="9.4.3" data-path="m3a-using-projects-and-scripts-in-r.html"><a href="m3a-using-projects-and-scripts-in-r.html#backing-up-your-project-folder"><i class="fa fa-check"></i><b>9.4.3</b> Backing Up Your Project Folder</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="m3a-using-projects-and-scripts-in-r.html"><a href="m3a-using-projects-and-scripts-in-r.html#conclusion-2"><i class="fa fa-check"></i><b>9.5</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="m3c-writing-in-r-markdown.html"><a href="m3c-writing-in-r-markdown.html"><i class="fa fa-check"></i><b>10</b> M3C: Writing in R Markdown</a>
<ul>
<li class="chapter" data-level="10.1" data-path="m3c-writing-in-r-markdown.html"><a href="m3c-writing-in-r-markdown.html#introduction-6"><i class="fa fa-check"></i><b>10.1</b> Introduction</a></li>
<li class="chapter" data-level="10.2" data-path="m3c-writing-in-r-markdown.html"><a href="m3c-writing-in-r-markdown.html#markdown-syntax"><i class="fa fa-check"></i><b>10.2</b> Markdown syntax</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="m3c-writing-in-r-markdown.html"><a href="m3c-writing-in-r-markdown.html#inline-formatting"><i class="fa fa-check"></i><b>10.2.1</b> Inline formatting</a></li>
<li class="chapter" data-level="10.2.2" data-path="m3c-writing-in-r-markdown.html"><a href="m3c-writing-in-r-markdown.html#block-level-elements"><i class="fa fa-check"></i><b>10.2.2</b> Block-level elements</a></li>
<li class="chapter" data-level="10.2.3" data-path="m3c-writing-in-r-markdown.html"><a href="m3c-writing-in-r-markdown.html#r-code-chunks"><i class="fa fa-check"></i><b>10.2.3</b> R code chunks</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="m3c-writing-in-r-markdown.html"><a href="m3c-writing-in-r-markdown.html#trying-out-r-markdown"><i class="fa fa-check"></i><b>10.3</b> Trying out R Markdown</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="m4u-the-value-of-open-data.html"><a href="m4u-the-value-of-open-data.html"><i class="fa fa-check"></i><b>11</b> M4U: The Value of Open Data</a>
<ul>
<li class="chapter" data-level="11.1" data-path="m4u-the-value-of-open-data.html"><a href="m4u-the-value-of-open-data.html#introduction-7"><i class="fa fa-check"></i><b>11.1</b> Introduction</a></li>
<li class="chapter" data-level="11.2" data-path="m4u-the-value-of-open-data.html"><a href="m4u-the-value-of-open-data.html#positivism-and-the-need-for-data"><i class="fa fa-check"></i><b>11.2</b> Positivism and the Need for Data</a></li>
<li class="chapter" data-level="11.3" data-path="m4u-the-value-of-open-data.html"><a href="m4u-the-value-of-open-data.html#sharing-data"><i class="fa fa-check"></i><b>11.3</b> Sharing Data</a></li>
<li class="chapter" data-level="11.4" data-path="m4u-the-value-of-open-data.html"><a href="m4u-the-value-of-open-data.html#sharing-data-and-privacy"><i class="fa fa-check"></i><b>11.4</b> Sharing Data and Privacy</a></li>
<li class="chapter" data-level="11.5" data-path="m4u-the-value-of-open-data.html"><a href="m4u-the-value-of-open-data.html#how-to-share-data"><i class="fa fa-check"></i><b>11.5</b> How to Share Data</a></li>
<li class="chapter" data-level="11.6" data-path="m4u-the-value-of-open-data.html"><a href="m4u-the-value-of-open-data.html#benefits-of-sharing-data"><i class="fa fa-check"></i><b>11.6</b> Benefits of Sharing Data</a></li>
<li class="chapter" data-level="11.7" data-path="m4u-the-value-of-open-data.html"><a href="m4u-the-value-of-open-data.html#downsides-of-sharing-data"><i class="fa fa-check"></i><b>11.7</b> Downsides of Sharing Data</a></li>
<li class="chapter" data-level="11.8" data-path="m4u-the-value-of-open-data.html"><a href="m4u-the-value-of-open-data.html#incentives-for-sharing-data"><i class="fa fa-check"></i><b>11.8</b> Incentives for Sharing Data</a></li>
<li class="chapter" data-level="11.9" data-path="m4u-the-value-of-open-data.html"><a href="m4u-the-value-of-open-data.html#conclusion-3"><i class="fa fa-check"></i><b>11.9</b> Conclusion</a></li>
<li class="chapter" data-level="11.10" data-path="m4u-the-value-of-open-data.html"><a href="m4u-the-value-of-open-data.html#references-3"><i class="fa fa-check"></i><b>11.10</b> References</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="m4a-find-a-dataset-relevant-to-you.html"><a href="m4a-find-a-dataset-relevant-to-you.html"><i class="fa fa-check"></i><b>12</b> M4A: Find a Dataset Relevant To You</a>
<ul>
<li class="chapter" data-level="12.1" data-path="m4a-find-a-dataset-relevant-to-you.html"><a href="m4a-find-a-dataset-relevant-to-you.html#introduction-8"><i class="fa fa-check"></i><b>12.1</b> Introduction</a></li>
<li class="chapter" data-level="12.2" data-path="m4a-find-a-dataset-relevant-to-you.html"><a href="m4a-find-a-dataset-relevant-to-you.html#signs-of-a-good-dataset"><i class="fa fa-check"></i><b>12.2</b> Signs of a Good Dataset</a></li>
<li class="chapter" data-level="12.3" data-path="m4a-find-a-dataset-relevant-to-you.html"><a href="m4a-find-a-dataset-relevant-to-you.html#finding-a-good-dataset"><i class="fa fa-check"></i><b>12.3</b> Finding a Good Dataset</a></li>
<li class="chapter" data-level="12.4" data-path="m4a-find-a-dataset-relevant-to-you.html"><a href="m4a-find-a-dataset-relevant-to-you.html#loading-dataset"><i class="fa fa-check"></i><b>12.4</b> Loading Your Dataset</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="m4c-show-your-work.html"><a href="m4c-show-your-work.html"><i class="fa fa-check"></i><b>13</b> M4C: Show Your Work</a>
<ul>
<li class="chapter" data-level="13.1" data-path="m4c-show-your-work.html"><a href="m4c-show-your-work.html#introduction-9"><i class="fa fa-check"></i><b>13.1</b> Introduction</a></li>
<li class="chapter" data-level="13.2" data-path="m4c-show-your-work.html"><a href="m4c-show-your-work.html#invisible-labor"><i class="fa fa-check"></i><b>13.2</b> Invisible Labor</a></li>
<li class="chapter" data-level="13.3" data-path="m4c-show-your-work.html"><a href="m4c-show-your-work.html#the-invisible-labor-of-data-science"><i class="fa fa-check"></i><b>13.3</b> The Invisible Labor of Data Science</a></li>
<li class="chapter" data-level="13.4" data-path="m4c-show-your-work.html"><a href="m4c-show-your-work.html#time-and-money"><i class="fa fa-check"></i><b>13.4</b> Time and Money</a></li>
<li class="chapter" data-level="13.5" data-path="m4c-show-your-work.html"><a href="m4c-show-your-work.html#crediting-data-work"><i class="fa fa-check"></i><b>13.5</b> Crediting Data Work</a></li>
<li class="chapter" data-level="13.6" data-path="m4c-show-your-work.html"><a href="m4c-show-your-work.html#crediting-emotional-labor-and-care-work"><i class="fa fa-check"></i><b>13.6</b> Crediting Emotional Labor and Care Work</a></li>
<li class="chapter" data-level="13.7" data-path="m4c-show-your-work.html"><a href="m4c-show-your-work.html#show-your-work"><i class="fa fa-check"></i><b>13.7</b> Show Your Work</a></li>
<li class="chapter" data-level="13.8" data-path="m4c-show-your-work.html"><a href="m4c-show-your-work.html#references-4"><i class="fa fa-check"></i><b>13.8</b> References</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="m5u-numbers-dont-speak-for-themselves.html"><a href="m5u-numbers-dont-speak-for-themselves.html"><i class="fa fa-check"></i><b>14</b> M5U: Numbers Don’t Speak for Themselves</a>
<ul>
<li class="chapter" data-level="14.1" data-path="m5u-numbers-dont-speak-for-themselves.html"><a href="m5u-numbers-dont-speak-for-themselves.html#introduction-10"><i class="fa fa-check"></i><b>14.1</b> Introduction</a></li>
<li class="chapter" data-level="14.2" data-path="m5u-numbers-dont-speak-for-themselves.html"><a href="m5u-numbers-dont-speak-for-themselves.html#bigger-is-not-always-better"><i class="fa fa-check"></i><b>14.2</b> Bigger is not Always Better</a></li>
<li class="chapter" data-level="14.3" data-path="m5u-numbers-dont-speak-for-themselves.html"><a href="m5u-numbers-dont-speak-for-themselves.html#theory"><i class="fa fa-check"></i><b>14.3</b> Theory</a></li>
<li class="chapter" data-level="14.4" data-path="m5u-numbers-dont-speak-for-themselves.html"><a href="m5u-numbers-dont-speak-for-themselves.html#the-importance-of-theory"><i class="fa fa-check"></i><b>14.4</b> The Importance of Theory</a></li>
<li class="chapter" data-level="14.5" data-path="m5u-numbers-dont-speak-for-themselves.html"><a href="m5u-numbers-dont-speak-for-themselves.html#research-isnt-just-empirical"><i class="fa fa-check"></i><b>14.5</b> Research isn’t Just Empirical</a></li>
<li class="chapter" data-level="14.6" data-path="m5u-numbers-dont-speak-for-themselves.html"><a href="m5u-numbers-dont-speak-for-themselves.html#the-importance-of-context"><i class="fa fa-check"></i><b>14.6</b> The Importance of Context</a></li>
<li class="chapter" data-level="14.7" data-path="m5u-numbers-dont-speak-for-themselves.html"><a href="m5u-numbers-dont-speak-for-themselves.html#conclusion-4"><i class="fa fa-check"></i><b>14.7</b> Conclusion</a></li>
<li class="chapter" data-level="14.8" data-path="m5u-numbers-dont-speak-for-themselves.html"><a href="m5u-numbers-dont-speak-for-themselves.html#references-5"><i class="fa fa-check"></i><b>14.8</b> References</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="m5a-are-ethics-enough-in-data-science.html"><a href="m5a-are-ethics-enough-in-data-science.html"><i class="fa fa-check"></i><b>15</b> M5A: Are Ethics Enough in Data Science?</a>
<ul>
<li class="chapter" data-level="15.1" data-path="m5a-are-ethics-enough-in-data-science.html"><a href="m5a-are-ethics-enough-in-data-science.html#introduction-11"><i class="fa fa-check"></i><b>15.1</b> Introduction</a></li>
<li class="chapter" data-level="15.2" data-path="m5a-are-ethics-enough-in-data-science.html"><a href="m5a-are-ethics-enough-in-data-science.html#ethics-vs.-politics"><i class="fa fa-check"></i><b>15.2</b> Ethics vs. Politics</a></li>
<li class="chapter" data-level="15.3" data-path="m5a-are-ethics-enough-in-data-science.html"><a href="m5a-are-ethics-enough-in-data-science.html#why-politics"><i class="fa fa-check"></i><b>15.3</b> Why Politics?</a>
<ul>
<li class="chapter" data-level="15.3.1" data-path="m5a-are-ethics-enough-in-data-science.html"><a href="m5a-are-ethics-enough-in-data-science.html#argument-1-i-am-just-an-engineer"><i class="fa fa-check"></i><b>15.3.1</b> Argument 1: “I am Just an Engineer”</a></li>
<li class="chapter" data-level="15.3.2" data-path="m5a-are-ethics-enough-in-data-science.html"><a href="m5a-are-ethics-enough-in-data-science.html#argument-2-we-shouldnt-take-political-stances"><i class="fa fa-check"></i><b>15.3.2</b> Argument 2: “We Shouldn’t Take Political Stances”</a></li>
<li class="chapter" data-level="15.3.3" data-path="m5a-are-ethics-enough-in-data-science.html"><a href="m5a-are-ethics-enough-in-data-science.html#argument-3-dont-let-the-perfect-be-the-enemy-of-the-good"><i class="fa fa-check"></i><b>15.3.3</b> Argument 3: “Don’t Let the Perfect Be the Enemy of the Good”</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="m5a-are-ethics-enough-in-data-science.html"><a href="m5a-are-ethics-enough-in-data-science.html#conclusion-5"><i class="fa fa-check"></i><b>15.4</b> Conclusion</a></li>
<li class="chapter" data-level="15.5" data-path="m5a-are-ethics-enough-in-data-science.html"><a href="m5a-are-ethics-enough-in-data-science.html#references-6"><i class="fa fa-check"></i><b>15.5</b> References</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="m5c-reflect-on-theoretical-and-philosophical-constraints.html"><a href="m5c-reflect-on-theoretical-and-philosophical-constraints.html"><i class="fa fa-check"></i><b>16</b> M5C: Reflect on Theoretical and Philosophical Constraints</a></li>
<li class="chapter" data-level="17" data-path="m6u-unicorns-janitors-and-rock-stars.html"><a href="m6u-unicorns-janitors-and-rock-stars.html"><i class="fa fa-check"></i><b>17</b> M6U: Unicorns, Janitors, and Rock Stars</a>
<ul>
<li class="chapter" data-level="17.1" data-path="m6u-unicorns-janitors-and-rock-stars.html"><a href="m6u-unicorns-janitors-and-rock-stars.html#introduction-12"><i class="fa fa-check"></i><b>17.1</b> Introduction</a></li>
<li class="chapter" data-level="17.2" data-path="m6u-unicorns-janitors-and-rock-stars.html"><a href="m6u-unicorns-janitors-and-rock-stars.html#intentionally-challenging-data-visualization"><i class="fa fa-check"></i><b>17.2</b> Intentionally Challenging Data Visualization</a></li>
<li class="chapter" data-level="17.3" data-path="m6u-unicorns-janitors-and-rock-stars.html"><a href="m6u-unicorns-janitors-and-rock-stars.html#sexy-scientists-and-drab-janitors"><i class="fa fa-check"></i><b>17.3</b> Sexy Scientists and… Drab Janitors?</a></li>
<li class="chapter" data-level="17.4" data-path="m6u-unicorns-janitors-and-rock-stars.html"><a href="m6u-unicorns-janitors-and-rock-stars.html#strangers-in-the-dataset"><i class="fa fa-check"></i><b>17.4</b> Strangers in the Dataset</a></li>
<li class="chapter" data-level="17.5" data-path="m6u-unicorns-janitors-and-rock-stars.html"><a href="m6u-unicorns-janitors-and-rock-stars.html#sharing-work-and-sharing-credit"><i class="fa fa-check"></i><b>17.5</b> Sharing Work and Sharing Credit</a></li>
<li class="chapter" data-level="17.6" data-path="m6u-unicorns-janitors-and-rock-stars.html"><a href="m6u-unicorns-janitors-and-rock-stars.html#conclusion-6"><i class="fa fa-check"></i><b>17.6</b> Conclusion</a></li>
<li class="chapter" data-level="17.7" data-path="m6u-unicorns-janitors-and-rock-stars.html"><a href="m6u-unicorns-janitors-and-rock-stars.html#references-7"><i class="fa fa-check"></i><b>17.7</b> References</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="m6a-wrangling-and-tidying-data.html"><a href="m6a-wrangling-and-tidying-data.html"><i class="fa fa-check"></i><b>18</b> M6A: Wrangling and Tidying Data</a>
<ul>
<li class="chapter" data-level="18.1" data-path="m6a-wrangling-and-tidying-data.html"><a href="m6a-wrangling-and-tidying-data.html#introduction-13"><i class="fa fa-check"></i><b>18.1</b> Introduction</a></li>
<li class="chapter" data-level="18.2" data-path="m6a-wrangling-and-tidying-data.html"><a href="m6a-wrangling-and-tidying-data.html#wrangling"><i class="fa fa-check"></i><b>18.2</b> Wrangling</a>
<ul>
<li class="chapter" data-level="" data-path="m6a-wrangling-and-tidying-data.html"><a href="m6a-wrangling-and-tidying-data.html#wrangling-packages"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="18.2.1" data-path="m6a-wrangling-and-tidying-data.html"><a href="m6a-wrangling-and-tidying-data.html#piping"><i class="fa fa-check"></i><b>18.2.1</b> The pipe operator: <code>%&gt;%</code></a></li>
<li class="chapter" data-level="18.2.2" data-path="m6a-wrangling-and-tidying-data.html"><a href="m6a-wrangling-and-tidying-data.html#filter"><i class="fa fa-check"></i><b>18.2.2</b> <code>filter</code> rows</a></li>
<li class="chapter" data-level="18.2.3" data-path="m6a-wrangling-and-tidying-data.html"><a href="m6a-wrangling-and-tidying-data.html#mutate"><i class="fa fa-check"></i><b>18.2.3</b> <code>mutate</code> existing variables</a></li>
<li class="chapter" data-level="18.2.4" data-path="m6a-wrangling-and-tidying-data.html"><a href="m6a-wrangling-and-tidying-data.html#arrange"><i class="fa fa-check"></i><b>18.2.4</b> <code>arrange</code> and sort rows</a></li>
<li class="chapter" data-level="18.2.5" data-path="m6a-wrangling-and-tidying-data.html"><a href="m6a-wrangling-and-tidying-data.html#select"><i class="fa fa-check"></i><b>18.2.5</b> <code>select</code> variables</a></li>
<li class="chapter" data-level="18.2.6" data-path="m6a-wrangling-and-tidying-data.html"><a href="m6a-wrangling-and-tidying-data.html#rename"><i class="fa fa-check"></i><b>18.2.6</b> <code>rename</code> variables</a></li>
<li class="chapter" data-level="18.2.7" data-path="m6a-wrangling-and-tidying-data.html"><a href="m6a-wrangling-and-tidying-data.html#top_n-values-of-a-variable"><i class="fa fa-check"></i><b>18.2.7</b> <code>top_n</code> values of a variable</a></li>
</ul></li>
<li class="chapter" data-level="18.3" data-path="m6a-wrangling-and-tidying-data.html"><a href="m6a-wrangling-and-tidying-data.html#tidying-data"><i class="fa fa-check"></i><b>18.3</b> Tidying Data</a>
<ul>
<li class="chapter" data-level="" data-path="m6a-wrangling-and-tidying-data.html"><a href="m6a-wrangling-and-tidying-data.html#tidy-packages"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="18.3.1" data-path="m6a-wrangling-and-tidying-data.html"><a href="m6a-wrangling-and-tidying-data.html#csv"><i class="fa fa-check"></i><b>18.3.1</b> Importing data</a></li>
<li class="chapter" data-level="18.3.2" data-path="m6a-wrangling-and-tidying-data.html"><a href="m6a-wrangling-and-tidying-data.html#tidy-data-ex"><i class="fa fa-check"></i><b>18.3.2</b> “Tidy” data</a></li>
<li class="chapter" data-level="18.3.3" data-path="m6a-wrangling-and-tidying-data.html"><a href="m6a-wrangling-and-tidying-data.html#tidy-definition"><i class="fa fa-check"></i><b>18.3.3</b> Definition of “tidy” data</a></li>
<li class="chapter" data-level="18.3.4" data-path="m6a-wrangling-and-tidying-data.html"><a href="m6a-wrangling-and-tidying-data.html#converting-to-tidy-data"><i class="fa fa-check"></i><b>18.3.4</b> Converting to “tidy” data</a></li>
<li class="chapter" data-level="18.3.5" data-path="m6a-wrangling-and-tidying-data.html"><a href="m6a-wrangling-and-tidying-data.html#case-study-tidy"><i class="fa fa-check"></i><b>18.3.5</b> Case study: Democracy in Guatemala</a></li>
</ul></li>
<li class="chapter" data-level="18.4" data-path="m6a-wrangling-and-tidying-data.html"><a href="m6a-wrangling-and-tidying-data.html#tidyverse-package"><i class="fa fa-check"></i><b>18.4</b> <code>tidyverse</code> package</a></li>
<li class="chapter" data-level="18.5" data-path="m6a-wrangling-and-tidying-data.html"><a href="m6a-wrangling-and-tidying-data.html#references-8"><i class="fa fa-check"></i><b>18.5</b> References</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="m6c-practice-wrangling-and-tidying-your-own-data.html"><a href="m6c-practice-wrangling-and-tidying-your-own-data.html"><i class="fa fa-check"></i><b>19</b> M6C: Practice Wrangling and Tidying Your Own Data</a></li>
<li class="chapter" data-level="20" data-path="m7u-subjectivity-in-data-visualization.html"><a href="m7u-subjectivity-in-data-visualization.html"><i class="fa fa-check"></i><b>20</b> M7U: Subjectivity in Data Visualization</a>
<ul>
<li class="chapter" data-level="20.1" data-path="m7u-subjectivity-in-data-visualization.html"><a href="m7u-subjectivity-in-data-visualization.html#introduction-14"><i class="fa fa-check"></i><b>20.1</b> Introduction</a></li>
<li class="chapter" data-level="20.2" data-path="m7u-subjectivity-in-data-visualization.html"><a href="m7u-subjectivity-in-data-visualization.html#persuasion-and-the-god-trick"><i class="fa fa-check"></i><b>20.2</b> Persuasion and the God Trick</a></li>
<li class="chapter" data-level="20.3" data-path="m7u-subjectivity-in-data-visualization.html"><a href="m7u-subjectivity-in-data-visualization.html#visualization-as-rhetoric"><i class="fa fa-check"></i><b>20.3</b> Visualization as Rhetoric</a></li>
<li class="chapter" data-level="20.4" data-path="m7u-subjectivity-in-data-visualization.html"><a href="m7u-subjectivity-in-data-visualization.html#editorial-choices-in-visualization"><i class="fa fa-check"></i><b>20.4</b> Editorial Choices in Visualization</a></li>
<li class="chapter" data-level="20.5" data-path="m7u-subjectivity-in-data-visualization.html"><a href="m7u-subjectivity-in-data-visualization.html#visualization-as-ideological-work"><i class="fa fa-check"></i><b>20.5</b> Visualization as Ideological Work</a></li>
<li class="chapter" data-level="20.6" data-path="m7u-subjectivity-in-data-visualization.html"><a href="m7u-subjectivity-in-data-visualization.html#feminist-objectivity"><i class="fa fa-check"></i><b>20.6</b> Feminist Objectivity</a></li>
<li class="chapter" data-level="20.7" data-path="m7u-subjectivity-in-data-visualization.html"><a href="m7u-subjectivity-in-data-visualization.html#data-visceralization"><i class="fa fa-check"></i><b>20.7</b> Data Visceralization</a></li>
<li class="chapter" data-level="20.8" data-path="m7u-subjectivity-in-data-visualization.html"><a href="m7u-subjectivity-in-data-visualization.html#conclusion-7"><i class="fa fa-check"></i><b>20.8</b> Conclusion</a></li>
<li class="chapter" data-level="20.9" data-path="m7u-subjectivity-in-data-visualization.html"><a href="m7u-subjectivity-in-data-visualization.html#references-9"><i class="fa fa-check"></i><b>20.9</b> References</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="viz.html"><a href="viz.html"><i class="fa fa-check"></i><b>21</b> M7A: Data Visualization</a></li>
<li class="part"><span><b>I Data Science with tidyverse</b></span></li>
<li class="chapter" data-level="22" data-path="data-visualization.html"><a href="data-visualization.html"><i class="fa fa-check"></i><b>22</b> Data Visualization</a>
<ul>
<li class="chapter" data-level="" data-path="data-visualization.html"><a href="data-visualization.html#needed-packages"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="22.1" data-path="data-visualization.html"><a href="data-visualization.html#grammarofgraphics"><i class="fa fa-check"></i><b>22.1</b> The grammar of graphics</a>
<ul>
<li class="chapter" data-level="22.1.1" data-path="data-visualization.html"><a href="data-visualization.html#components-of-the-grammar"><i class="fa fa-check"></i><b>22.1.1</b> Components of the grammar</a></li>
<li class="chapter" data-level="22.1.2" data-path="data-visualization.html"><a href="data-visualization.html#gapminder"><i class="fa fa-check"></i><b>22.1.2</b> Gapminder data</a></li>
<li class="chapter" data-level="22.1.3" data-path="data-visualization.html"><a href="data-visualization.html#other-components"><i class="fa fa-check"></i><b>22.1.3</b> Other components</a></li>
<li class="chapter" data-level="22.1.4" data-path="data-visualization.html"><a href="data-visualization.html#ggplot2-package"><i class="fa fa-check"></i><b>22.1.4</b> ggplot2 package</a></li>
</ul></li>
<li class="chapter" data-level="22.2" data-path="data-visualization.html"><a href="data-visualization.html#FiveNG"><i class="fa fa-check"></i><b>22.2</b> Five named graphs - the 5NG</a></li>
<li class="chapter" data-level="22.3" data-path="data-visualization.html"><a href="data-visualization.html#scatterplots"><i class="fa fa-check"></i><b>22.3</b> 5NG#1: Scatterplots</a>
<ul>
<li class="chapter" data-level="22.3.1" data-path="data-visualization.html"><a href="data-visualization.html#geompoint"><i class="fa fa-check"></i><b>22.3.1</b> Scatterplots via <code>geom_point</code></a></li>
<li class="chapter" data-level="22.3.2" data-path="data-visualization.html"><a href="data-visualization.html#overplotting"><i class="fa fa-check"></i><b>22.3.2</b> Overplotting</a></li>
<li class="chapter" data-level="22.3.3" data-path="data-visualization.html"><a href="data-visualization.html#summary"><i class="fa fa-check"></i><b>22.3.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="22.4" data-path="data-visualization.html"><a href="data-visualization.html#linegraphs"><i class="fa fa-check"></i><b>22.4</b> 5NG#2: Linegraphs</a>
<ul>
<li class="chapter" data-level="22.4.1" data-path="data-visualization.html"><a href="data-visualization.html#geomline"><i class="fa fa-check"></i><b>22.4.1</b> Linegraphs via <code>geom_line</code></a></li>
<li class="chapter" data-level="22.4.2" data-path="data-visualization.html"><a href="data-visualization.html#summary-1"><i class="fa fa-check"></i><b>22.4.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="22.5" data-path="data-visualization.html"><a href="data-visualization.html#histograms"><i class="fa fa-check"></i><b>22.5</b> 5NG#3: Histograms</a>
<ul>
<li class="chapter" data-level="22.5.1" data-path="data-visualization.html"><a href="data-visualization.html#geomhistogram"><i class="fa fa-check"></i><b>22.5.1</b> Histograms via <code>geom_histogram</code></a></li>
<li class="chapter" data-level="22.5.2" data-path="data-visualization.html"><a href="data-visualization.html#adjustbins"><i class="fa fa-check"></i><b>22.5.2</b> Adjusting the bins</a></li>
<li class="chapter" data-level="22.5.3" data-path="data-visualization.html"><a href="data-visualization.html#summary-2"><i class="fa fa-check"></i><b>22.5.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="22.6" data-path="data-visualization.html"><a href="data-visualization.html#facets"><i class="fa fa-check"></i><b>22.6</b> Facets</a></li>
<li class="chapter" data-level="22.7" data-path="data-visualization.html"><a href="data-visualization.html#boxplots"><i class="fa fa-check"></i><b>22.7</b> 5NG#4: Boxplots</a>
<ul>
<li class="chapter" data-level="22.7.1" data-path="data-visualization.html"><a href="data-visualization.html#geomboxplot"><i class="fa fa-check"></i><b>22.7.1</b> Boxplots via <code>geom_boxplot</code></a></li>
<li class="chapter" data-level="22.7.2" data-path="data-visualization.html"><a href="data-visualization.html#summary-3"><i class="fa fa-check"></i><b>22.7.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="22.8" data-path="data-visualization.html"><a href="data-visualization.html#geombar"><i class="fa fa-check"></i><b>22.8</b> 5NG#5: Barplots</a>
<ul>
<li class="chapter" data-level="22.8.1" data-path="data-visualization.html"><a href="data-visualization.html#barplots-via-geom_bar-or-geom_col"><i class="fa fa-check"></i><b>22.8.1</b> Barplots via <code>geom_bar</code> or <code>geom_col</code></a></li>
<li class="chapter" data-level="22.8.2" data-path="data-visualization.html"><a href="data-visualization.html#must-avoid-pie-charts"><i class="fa fa-check"></i><b>22.8.2</b> Must avoid pie charts!</a></li>
<li class="chapter" data-level="22.8.3" data-path="data-visualization.html"><a href="data-visualization.html#two-categ-barplot"><i class="fa fa-check"></i><b>22.8.3</b> Two categorical variables</a></li>
<li class="chapter" data-level="22.8.4" data-path="data-visualization.html"><a href="data-visualization.html#summary-4"><i class="fa fa-check"></i><b>22.8.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="22.9" data-path="data-visualization.html"><a href="data-visualization.html#data-vis-conclusion"><i class="fa fa-check"></i><b>22.9</b> Conclusion</a>
<ul>
<li class="chapter" data-level="22.9.1" data-path="data-visualization.html"><a href="data-visualization.html#summary-table"><i class="fa fa-check"></i><b>22.9.1</b> Summary table</a></li>
<li class="chapter" data-level="22.9.2" data-path="data-visualization.html"><a href="data-visualization.html#function-argument-specification"><i class="fa fa-check"></i><b>22.9.2</b> Function argument specification</a></li>
<li class="chapter" data-level="22.9.3" data-path="data-visualization.html"><a href="data-visualization.html#additional-resources"><i class="fa fa-check"></i><b>22.9.3</b> Additional resources</a></li>
<li class="chapter" data-level="22.9.4" data-path="data-visualization.html"><a href="data-visualization.html#whats-to-come-3"><i class="fa fa-check"></i><b>22.9.4</b> What’s to come</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="23" data-path="m7c-practice-visualizing-your-own-data.html"><a href="m7c-practice-visualizing-your-own-data.html"><i class="fa fa-check"></i><b>23</b> M7C: Practice Visualizing Your Own Data</a></li>
<li class="chapter" data-level="24" data-path="module-8-understanding.html"><a href="module-8-understanding.html"><i class="fa fa-check"></i><b>24</b> Module 8 Understanding</a></li>
<li class="chapter" data-level="25" data-path="m8a-descriptive-statistics.html"><a href="m8a-descriptive-statistics.html"><i class="fa fa-check"></i><b>25</b> M8A: Descriptive Statistics</a>
<ul>
<li class="chapter" data-level="25.1" data-path="m8a-descriptive-statistics.html"><a href="m8a-descriptive-statistics.html#summarize"><i class="fa fa-check"></i><b>25.1</b> <code>summarize</code> variables</a></li>
<li class="chapter" data-level="25.2" data-path="m8a-descriptive-statistics.html"><a href="m8a-descriptive-statistics.html#groupby"><i class="fa fa-check"></i><b>25.2</b> <code>group_by</code> rows</a>
<ul>
<li class="chapter" data-level="25.2.1" data-path="m8a-descriptive-statistics.html"><a href="m8a-descriptive-statistics.html#grouping-by-more-than-one-variable"><i class="fa fa-check"></i><b>25.2.1</b> Grouping by more than one variable</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="26" data-path="m8c-calculate-descriptive-statistics-for-your-own-data.html"><a href="m8c-calculate-descriptive-statistics-for-your-own-data.html"><i class="fa fa-check"></i><b>26</b> M8C: Calculate Descriptive Statistics for Your Own Data</a></li>
<li class="chapter" data-level="27" data-path="module-9-understanding.html"><a href="module-9-understanding.html"><i class="fa fa-check"></i><b>27</b> Module 9 Understanding</a></li>
<li class="chapter" data-level="28" data-path="m9a-basic-regression.html"><a href="m9a-basic-regression.html"><i class="fa fa-check"></i><b>28</b> M9A: Basic Regression</a>
<ul>
<li class="chapter" data-level="" data-path="m9a-basic-regression.html"><a href="m9a-basic-regression.html#reg-packages"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="28.1" data-path="m9a-basic-regression.html"><a href="m9a-basic-regression.html#model1"><i class="fa fa-check"></i><b>28.1</b> One numerical explanatory variable</a>
<ul>
<li class="chapter" data-level="28.1.1" data-path="m9a-basic-regression.html"><a href="m9a-basic-regression.html#model1EDA"><i class="fa fa-check"></i><b>28.1.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="28.1.2" data-path="m9a-basic-regression.html"><a href="m9a-basic-regression.html#model1table"><i class="fa fa-check"></i><b>28.1.2</b> Simple linear regression</a></li>
<li class="chapter" data-level="28.1.3" data-path="m9a-basic-regression.html"><a href="m9a-basic-regression.html#model1points"><i class="fa fa-check"></i><b>28.1.3</b> Observed/fitted values and residuals</a></li>
</ul></li>
<li class="chapter" data-level="28.2" data-path="m9a-basic-regression.html"><a href="m9a-basic-regression.html#model2"><i class="fa fa-check"></i><b>28.2</b> One categorical explanatory variable</a>
<ul>
<li class="chapter" data-level="28.2.1" data-path="m9a-basic-regression.html"><a href="m9a-basic-regression.html#model2EDA"><i class="fa fa-check"></i><b>28.2.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="28.2.2" data-path="m9a-basic-regression.html"><a href="m9a-basic-regression.html#model2table"><i class="fa fa-check"></i><b>28.2.2</b> Linear regression</a></li>
<li class="chapter" data-level="28.2.3" data-path="m9a-basic-regression.html"><a href="m9a-basic-regression.html#model2points"><i class="fa fa-check"></i><b>28.2.3</b> Observed/fitted values and residuals</a></li>
</ul></li>
<li class="chapter" data-level="28.3" data-path="m9a-basic-regression.html"><a href="m9a-basic-regression.html#reg-related-topics"><i class="fa fa-check"></i><b>28.3</b> Related topics</a>
<ul>
<li class="chapter" data-level="28.3.1" data-path="m9a-basic-regression.html"><a href="m9a-basic-regression.html#correlation-is-not-causation"><i class="fa fa-check"></i><b>28.3.1</b> Correlation is not necessarily causation</a></li>
<li class="chapter" data-level="28.3.2" data-path="m9a-basic-regression.html"><a href="m9a-basic-regression.html#leastsquares"><i class="fa fa-check"></i><b>28.3.2</b> Best-fitting line</a></li>
<li class="chapter" data-level="28.3.3" data-path="m9a-basic-regression.html"><a href="m9a-basic-regression.html#underthehood"><i class="fa fa-check"></i><b>28.3.3</b> <code>get_regression_x()</code> functions</a></li>
</ul></li>
<li class="chapter" data-level="28.4" data-path="m9a-basic-regression.html"><a href="m9a-basic-regression.html#reg-conclusion"><i class="fa fa-check"></i><b>28.4</b> Conclusion</a>
<ul>
<li class="chapter" data-level="28.4.1" data-path="m9a-basic-regression.html"><a href="m9a-basic-regression.html#additional-resources-basic-regression"><i class="fa fa-check"></i><b>28.4.1</b> Additional resources</a></li>
<li class="chapter" data-level="28.4.2" data-path="m9a-basic-regression.html"><a href="m9a-basic-regression.html#whats-to-come"><i class="fa fa-check"></i><b>28.4.2</b> What’s to come?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="29" data-path="m9c-perform-a-basic-regression-with-your-own-data.html"><a href="m9c-perform-a-basic-regression-with-your-own-data.html"><i class="fa fa-check"></i><b>29</b> M9C: Perform a Basic Regression With Your Own Data</a></li>
<li class="chapter" data-level="30" data-path="module-10-understanding.html"><a href="module-10-understanding.html"><i class="fa fa-check"></i><b>30</b> Module 10 Understanding</a></li>
<li class="chapter" data-level="31" data-path="m10a-multiple-regression.html"><a href="m10a-multiple-regression.html"><i class="fa fa-check"></i><b>31</b> M10A: Multiple Regression</a>
<ul>
<li class="chapter" data-level="" data-path="m10a-multiple-regression.html"><a href="m10a-multiple-regression.html#mult-reg-packages"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="31.1" data-path="m10a-multiple-regression.html"><a href="m10a-multiple-regression.html#model4"><i class="fa fa-check"></i><b>31.1</b> One numerical and one categorical explanatory variable</a>
<ul>
<li class="chapter" data-level="31.1.1" data-path="m10a-multiple-regression.html"><a href="m10a-multiple-regression.html#model4EDA"><i class="fa fa-check"></i><b>31.1.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="31.1.2" data-path="m10a-multiple-regression.html"><a href="m10a-multiple-regression.html#model4interactiontable"><i class="fa fa-check"></i><b>31.1.2</b> Interaction model</a></li>
<li class="chapter" data-level="31.1.3" data-path="m10a-multiple-regression.html"><a href="m10a-multiple-regression.html#model4table"><i class="fa fa-check"></i><b>31.1.3</b> Parallel slopes model</a></li>
<li class="chapter" data-level="31.1.4" data-path="m10a-multiple-regression.html"><a href="m10a-multiple-regression.html#model4points"><i class="fa fa-check"></i><b>31.1.4</b> Observed/fitted values and residuals</a></li>
</ul></li>
<li class="chapter" data-level="31.2" data-path="m10a-multiple-regression.html"><a href="m10a-multiple-regression.html#model3"><i class="fa fa-check"></i><b>31.2</b> Two numerical explanatory variables</a>
<ul>
<li class="chapter" data-level="31.2.1" data-path="m10a-multiple-regression.html"><a href="m10a-multiple-regression.html#model3EDA"><i class="fa fa-check"></i><b>31.2.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="31.2.2" data-path="m10a-multiple-regression.html"><a href="m10a-multiple-regression.html#model3table"><i class="fa fa-check"></i><b>31.2.2</b> Regression plane</a></li>
<li class="chapter" data-level="31.2.3" data-path="m10a-multiple-regression.html"><a href="m10a-multiple-regression.html#model3points"><i class="fa fa-check"></i><b>31.2.3</b> Observed/fitted values and residuals</a></li>
</ul></li>
<li class="chapter" data-level="31.3" data-path="m10a-multiple-regression.html"><a href="m10a-multiple-regression.html#mult-reg-related-topics"><i class="fa fa-check"></i><b>31.3</b> Related topics</a>
<ul>
<li class="chapter" data-level="31.3.1" data-path="m10a-multiple-regression.html"><a href="m10a-multiple-regression.html#model-selection"><i class="fa fa-check"></i><b>31.3.1</b> Model selection using visualizations</a></li>
<li class="chapter" data-level="31.3.2" data-path="m10a-multiple-regression.html"><a href="m10a-multiple-regression.html#rsquared"><i class="fa fa-check"></i><b>31.3.2</b> Model selection using R-squared</a></li>
<li class="chapter" data-level="31.3.3" data-path="m10a-multiple-regression.html"><a href="m10a-multiple-regression.html#correlationcoefficient2"><i class="fa fa-check"></i><b>31.3.3</b> Correlation coefficient</a></li>
<li class="chapter" data-level="31.3.4" data-path="m10a-multiple-regression.html"><a href="m10a-multiple-regression.html#simpsonsparadox"><i class="fa fa-check"></i><b>31.3.4</b> Simpson’s Paradox</a></li>
</ul></li>
<li class="chapter" data-level="31.4" data-path="m10a-multiple-regression.html"><a href="m10a-multiple-regression.html#mult-reg-conclusion"><i class="fa fa-check"></i><b>31.4</b> Conclusion</a>
<ul>
<li class="chapter" data-level="31.4.1" data-path="m10a-multiple-regression.html"><a href="m10a-multiple-regression.html#additional-resources-1"><i class="fa fa-check"></i><b>31.4.1</b> Additional resources</a></li>
<li class="chapter" data-level="31.4.2" data-path="m10a-multiple-regression.html"><a href="m10a-multiple-regression.html#whats-to-come-1"><i class="fa fa-check"></i><b>31.4.2</b> What’s to come?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="32" data-path="m10c-perform-a-multiple-regression-with-your-own-data.html"><a href="m10c-perform-a-multiple-regression-with-your-own-data.html"><i class="fa fa-check"></i><b>32</b> M10C: Perform a Multiple Regression With Your Own Data</a></li>
<li class="chapter" data-level="33" data-path="module-11-understanding.html"><a href="module-11-understanding.html"><i class="fa fa-check"></i><b>33</b> Module 11 Understanding</a></li>
<li class="chapter" data-level="34" data-path="m11a-sampling.html"><a href="m11a-sampling.html"><i class="fa fa-check"></i><b>34</b> M11A: Sampling</a>
<ul>
<li class="chapter" data-level="" data-path="m11a-sampling.html"><a href="m11a-sampling.html#sampling-packages"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="34.1" data-path="m11a-sampling.html"><a href="m11a-sampling.html#sampling-activity"><i class="fa fa-check"></i><b>34.1</b> Sampling bowl activity</a>
<ul>
<li class="chapter" data-level="34.1.1" data-path="m11a-sampling.html"><a href="m11a-sampling.html#what-proportion-of-this-bowls-balls-are-red"><i class="fa fa-check"></i><b>34.1.1</b> What proportion of this bowl’s balls are red?</a></li>
<li class="chapter" data-level="34.1.2" data-path="m11a-sampling.html"><a href="m11a-sampling.html#using-the-shovel-once"><i class="fa fa-check"></i><b>34.1.2</b> Using the shovel once</a></li>
<li class="chapter" data-level="34.1.3" data-path="m11a-sampling.html"><a href="m11a-sampling.html#student-shovels"><i class="fa fa-check"></i><b>34.1.3</b> Using the shovel 33 times</a></li>
<li class="chapter" data-level="34.1.4" data-path="m11a-sampling.html"><a href="m11a-sampling.html#sampling-what-did-we-just-do"><i class="fa fa-check"></i><b>34.1.4</b> What did we just do?</a></li>
</ul></li>
<li class="chapter" data-level="34.2" data-path="m11a-sampling.html"><a href="m11a-sampling.html#sampling-simulation"><i class="fa fa-check"></i><b>34.2</b> Virtual sampling</a>
<ul>
<li class="chapter" data-level="34.2.1" data-path="m11a-sampling.html"><a href="m11a-sampling.html#using-the-virtual-shovel-once"><i class="fa fa-check"></i><b>34.2.1</b> Using the virtual shovel once</a></li>
<li class="chapter" data-level="34.2.2" data-path="m11a-sampling.html"><a href="m11a-sampling.html#using-the-virtual-shovel-33-times"><i class="fa fa-check"></i><b>34.2.2</b> Using the virtual shovel 33 times</a></li>
<li class="chapter" data-level="34.2.3" data-path="m11a-sampling.html"><a href="m11a-sampling.html#shovel-1000-times"><i class="fa fa-check"></i><b>34.2.3</b> Using the virtual shovel 1000 times</a></li>
<li class="chapter" data-level="34.2.4" data-path="m11a-sampling.html"><a href="m11a-sampling.html#different-shovels"><i class="fa fa-check"></i><b>34.2.4</b> Using different shovels</a></li>
</ul></li>
<li class="chapter" data-level="34.3" data-path="m11a-sampling.html"><a href="m11a-sampling.html#sampling-framework"><i class="fa fa-check"></i><b>34.3</b> Sampling framework</a>
<ul>
<li class="chapter" data-level="34.3.1" data-path="m11a-sampling.html"><a href="m11a-sampling.html#terminology-and-notation"><i class="fa fa-check"></i><b>34.3.1</b> Terminology and notation</a></li>
<li class="chapter" data-level="34.3.2" data-path="m11a-sampling.html"><a href="m11a-sampling.html#sampling-definitions"><i class="fa fa-check"></i><b>34.3.2</b> Statistical definitions</a></li>
<li class="chapter" data-level="34.3.3" data-path="m11a-sampling.html"><a href="m11a-sampling.html#moral-of-the-story"><i class="fa fa-check"></i><b>34.3.3</b> The moral of the story</a></li>
</ul></li>
<li class="chapter" data-level="34.4" data-path="m11a-sampling.html"><a href="m11a-sampling.html#sampling-case-study"><i class="fa fa-check"></i><b>34.4</b> Case study: Polls</a></li>
<li class="chapter" data-level="34.5" data-path="m11a-sampling.html"><a href="m11a-sampling.html#sampling-conclusion-central-limit-theorem"><i class="fa fa-check"></i><b>34.5</b> Central Limit Theorem</a></li>
<li class="chapter" data-level="34.6" data-path="m11a-sampling.html"><a href="m11a-sampling.html#sampling-conclusion"><i class="fa fa-check"></i><b>34.6</b> Conclusion</a>
<ul>
<li class="chapter" data-level="34.6.1" data-path="m11a-sampling.html"><a href="m11a-sampling.html#sampling-conclusion-table"><i class="fa fa-check"></i><b>34.6.1</b> Sampling scenarios</a></li>
<li class="chapter" data-level="34.6.2" data-path="m11a-sampling.html"><a href="m11a-sampling.html#theory-se"><i class="fa fa-check"></i><b>34.6.2</b> Theory-based standard-errors</a></li>
<li class="chapter" data-level="34.6.3" data-path="m11a-sampling.html"><a href="m11a-sampling.html#additional-resources-2"><i class="fa fa-check"></i><b>34.6.3</b> Additional resources</a></li>
<li class="chapter" data-level="34.6.4" data-path="m11a-sampling.html"><a href="m11a-sampling.html#whats-to-come-2"><i class="fa fa-check"></i><b>34.6.4</b> What’s to come?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="35" data-path="m11c-explore-sampling-with-your-own.html"><a href="m11c-explore-sampling-with-your-own.html"><i class="fa fa-check"></i><b>35</b> M11C: Explore Sampling With Your Own</a></li>
<li class="chapter" data-level="36" data-path="module-12-understanding.html"><a href="module-12-understanding.html"><i class="fa fa-check"></i><b>36</b> Module 12 Understanding</a></li>
<li class="chapter" data-level="37" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html"><i class="fa fa-check"></i><b>37</b> M12A: Confidence Intervals</a>
<ul>
<li class="chapter" data-level="" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html#CI-packages"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="37.1" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html#resampling-tactile"><i class="fa fa-check"></i><b>37.1</b> Pennies activity</a>
<ul>
<li class="chapter" data-level="37.1.1" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html#what-is-the-average-year-on-us-pennies-in-2019"><i class="fa fa-check"></i><b>37.1.1</b> What is the average year on US pennies in 2019?</a></li>
<li class="chapter" data-level="37.1.2" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html#resampling-once"><i class="fa fa-check"></i><b>37.1.2</b> Resampling once</a></li>
<li class="chapter" data-level="37.1.3" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html#student-resamples"><i class="fa fa-check"></i><b>37.1.3</b> Resampling 35 times</a></li>
<li class="chapter" data-level="37.1.4" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html#ci-what-did-we-just-do"><i class="fa fa-check"></i><b>37.1.4</b> What did we just do?</a></li>
</ul></li>
<li class="chapter" data-level="37.2" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html#resampling-simulation"><i class="fa fa-check"></i><b>37.2</b> Computer simulation of resampling</a>
<ul>
<li class="chapter" data-level="37.2.1" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html#virtually-resampling-once"><i class="fa fa-check"></i><b>37.2.1</b> Virtually resampling once</a></li>
<li class="chapter" data-level="37.2.2" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html#bootstrap-35-replicates"><i class="fa fa-check"></i><b>37.2.2</b> Virtually resampling 35 times</a></li>
<li class="chapter" data-level="37.2.3" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html#bootstrap-1000-replicates"><i class="fa fa-check"></i><b>37.2.3</b> Virtually resampling 1000 times</a></li>
</ul></li>
<li class="chapter" data-level="37.3" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html#ci-build-up"><i class="fa fa-check"></i><b>37.3</b> Understanding confidence intervals</a>
<ul>
<li class="chapter" data-level="37.3.1" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html#percentile-method"><i class="fa fa-check"></i><b>37.3.1</b> Percentile method</a></li>
<li class="chapter" data-level="37.3.2" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html#se-method"><i class="fa fa-check"></i><b>37.3.2</b> Standard error method</a></li>
</ul></li>
<li class="chapter" data-level="37.4" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html#bootstrap-process"><i class="fa fa-check"></i><b>37.4</b> Constructing confidence intervals</a>
<ul>
<li class="chapter" data-level="37.4.1" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html#original-workflow"><i class="fa fa-check"></i><b>37.4.1</b> Original workflow</a></li>
<li class="chapter" data-level="37.4.2" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html#infer-workflow"><i class="fa fa-check"></i><b>37.4.2</b> <code>infer</code> package workflow</a></li>
<li class="chapter" data-level="37.4.3" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html#percentile-method-infer"><i class="fa fa-check"></i><b>37.4.3</b> Percentile method with <code>infer</code></a></li>
<li class="chapter" data-level="37.4.4" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html#infer-se"><i class="fa fa-check"></i><b>37.4.4</b> Standard error method with <code>infer</code></a></li>
</ul></li>
<li class="chapter" data-level="37.5" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html#one-prop-ci"><i class="fa fa-check"></i><b>37.5</b> Interpreting confidence intervals</a>
<ul>
<li class="chapter" data-level="37.5.1" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html#ilyas-yohan"><i class="fa fa-check"></i><b>37.5.1</b> Did the net capture the fish?</a></li>
<li class="chapter" data-level="37.5.2" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html#shorthand"><i class="fa fa-check"></i><b>37.5.2</b> Precise and shorthand interpretation</a></li>
<li class="chapter" data-level="37.5.3" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html#ci-width"><i class="fa fa-check"></i><b>37.5.3</b> Width of confidence intervals</a></li>
</ul></li>
<li class="chapter" data-level="37.6" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html#case-study-two-prop-ci"><i class="fa fa-check"></i><b>37.6</b> Case study: Is yawning contagious?</a>
<ul>
<li class="chapter" data-level="37.6.1" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html#mythbusters-study-data"><i class="fa fa-check"></i><b>37.6.1</b> <em>Mythbusters</em> study data</a></li>
<li class="chapter" data-level="37.6.2" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html#sampling-scenario"><i class="fa fa-check"></i><b>37.6.2</b> Sampling scenario</a></li>
<li class="chapter" data-level="37.6.3" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html#ci-build"><i class="fa fa-check"></i><b>37.6.3</b> Constructing the confidence interval</a></li>
<li class="chapter" data-level="37.6.4" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html#interpreting-the-confidence-interval"><i class="fa fa-check"></i><b>37.6.4</b> Interpreting the confidence interval</a></li>
</ul></li>
<li class="chapter" data-level="37.7" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html#ci-conclusion"><i class="fa fa-check"></i><b>37.7</b> Conclusion</a>
<ul>
<li class="chapter" data-level="37.7.1" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html#bootstrap-vs-sampling"><i class="fa fa-check"></i><b>37.7.1</b> Comparing bootstrap and sampling distributions</a></li>
<li class="chapter" data-level="37.7.2" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html#theory-ci"><i class="fa fa-check"></i><b>37.7.2</b> Theory-based confidence intervals</a></li>
<li class="chapter" data-level="37.7.3" data-path="m12a-confidence-intervals.html"><a href="m12a-confidence-intervals.html#whats-to-come-4"><i class="fa fa-check"></i><b>37.7.3</b> What’s to come?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="38" data-path="m12c-explore-confidence-intervals-with-your-own-data.html"><a href="m12c-explore-confidence-intervals-with-your-own-data.html"><i class="fa fa-check"></i><b>38</b> M12C: Explore Confidence Intervals With Your Own Data</a></li>
<li class="chapter" data-level="39" data-path="module-13-understanding.html"><a href="module-13-understanding.html"><i class="fa fa-check"></i><b>39</b> Module 13 Understanding</a></li>
<li class="chapter" data-level="40" data-path="m13a-hypothesis-testing.html"><a href="m13a-hypothesis-testing.html"><i class="fa fa-check"></i><b>40</b> M13A: Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="" data-path="m13a-hypothesis-testing.html"><a href="m13a-hypothesis-testing.html#nhst-packages"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="40.1" data-path="m13a-hypothesis-testing.html"><a href="m13a-hypothesis-testing.html#ht-activity"><i class="fa fa-check"></i><b>40.1</b> Promotions activity</a>
<ul>
<li class="chapter" data-level="40.1.1" data-path="m13a-hypothesis-testing.html"><a href="m13a-hypothesis-testing.html#does-gender-affect-promotions-at-a-bank"><i class="fa fa-check"></i><b>40.1.1</b> Does gender affect promotions at a bank?</a></li>
<li class="chapter" data-level="40.1.2" data-path="m13a-hypothesis-testing.html"><a href="m13a-hypothesis-testing.html#shuffling-once"><i class="fa fa-check"></i><b>40.1.2</b> Shuffling once</a></li>
<li class="chapter" data-level="40.1.3" data-path="m13a-hypothesis-testing.html"><a href="m13a-hypothesis-testing.html#shuffling-16-times"><i class="fa fa-check"></i><b>40.1.3</b> Shuffling 16 times</a></li>
<li class="chapter" data-level="40.1.4" data-path="m13a-hypothesis-testing.html"><a href="m13a-hypothesis-testing.html#ht-what-did-we-just-do"><i class="fa fa-check"></i><b>40.1.4</b> What did we just do?</a></li>
</ul></li>
<li class="chapter" data-level="40.2" data-path="m13a-hypothesis-testing.html"><a href="m13a-hypothesis-testing.html#understanding-ht"><i class="fa fa-check"></i><b>40.2</b> Understanding hypothesis tests</a></li>
<li class="chapter" data-level="40.3" data-path="m13a-hypothesis-testing.html"><a href="m13a-hypothesis-testing.html#ht-infer"><i class="fa fa-check"></i><b>40.3</b> Conducting hypothesis tests</a>
<ul>
<li class="chapter" data-level="40.3.1" data-path="m13a-hypothesis-testing.html"><a href="m13a-hypothesis-testing.html#infer-workflow-ht"><i class="fa fa-check"></i><b>40.3.1</b> <code>infer</code> package workflow</a></li>
<li class="chapter" data-level="40.3.2" data-path="m13a-hypothesis-testing.html"><a href="m13a-hypothesis-testing.html#comparing-infer-workflows"><i class="fa fa-check"></i><b>40.3.2</b> Comparison with confidence intervals</a></li>
<li class="chapter" data-level="40.3.3" data-path="m13a-hypothesis-testing.html"><a href="m13a-hypothesis-testing.html#only-one-test"><i class="fa fa-check"></i><b>40.3.3</b> “There is only one test”</a></li>
</ul></li>
<li class="chapter" data-level="40.4" data-path="m13a-hypothesis-testing.html"><a href="m13a-hypothesis-testing.html#ht-interpretation"><i class="fa fa-check"></i><b>40.4</b> Interpreting hypothesis tests</a>
<ul>
<li class="chapter" data-level="40.4.1" data-path="m13a-hypothesis-testing.html"><a href="m13a-hypothesis-testing.html#trial"><i class="fa fa-check"></i><b>40.4.1</b> Two possible outcomes</a></li>
<li class="chapter" data-level="40.4.2" data-path="m13a-hypothesis-testing.html"><a href="m13a-hypothesis-testing.html#types-of-errors"><i class="fa fa-check"></i><b>40.4.2</b> Types of errors</a></li>
<li class="chapter" data-level="40.4.3" data-path="m13a-hypothesis-testing.html"><a href="m13a-hypothesis-testing.html#choosing-alpha"><i class="fa fa-check"></i><b>40.4.3</b> How do we choose alpha?</a></li>
</ul></li>
<li class="chapter" data-level="40.5" data-path="m13a-hypothesis-testing.html"><a href="m13a-hypothesis-testing.html#ht-case-study"><i class="fa fa-check"></i><b>40.5</b> Case study: Are action or romance movies rated higher?</a>
<ul>
<li class="chapter" data-level="40.5.1" data-path="m13a-hypothesis-testing.html"><a href="m13a-hypothesis-testing.html#imdb-data"><i class="fa fa-check"></i><b>40.5.1</b> IMDb ratings data</a></li>
<li class="chapter" data-level="40.5.2" data-path="m13a-hypothesis-testing.html"><a href="m13a-hypothesis-testing.html#sampling-scenario-1"><i class="fa fa-check"></i><b>40.5.2</b> Sampling scenario</a></li>
<li class="chapter" data-level="40.5.3" data-path="m13a-hypothesis-testing.html"><a href="m13a-hypothesis-testing.html#conducting-the-hypothesis-test"><i class="fa fa-check"></i><b>40.5.3</b> Conducting the hypothesis test</a></li>
</ul></li>
<li class="chapter" data-level="40.6" data-path="m13a-hypothesis-testing.html"><a href="m13a-hypothesis-testing.html#nhst-conclusion"><i class="fa fa-check"></i><b>40.6</b> Conclusion</a>
<ul>
<li class="chapter" data-level="40.6.1" data-path="m13a-hypothesis-testing.html"><a href="m13a-hypothesis-testing.html#theory-hypo"><i class="fa fa-check"></i><b>40.6.1</b> Theory-based hypothesis tests</a></li>
<li class="chapter" data-level="40.6.2" data-path="m13a-hypothesis-testing.html"><a href="m13a-hypothesis-testing.html#when-inference-is-not-needed"><i class="fa fa-check"></i><b>40.6.2</b> When inference is not needed</a></li>
<li class="chapter" data-level="40.6.3" data-path="m13a-hypothesis-testing.html"><a href="m13a-hypothesis-testing.html#problems-with-p-values"><i class="fa fa-check"></i><b>40.6.3</b> Problems with p-values</a></li>
<li class="chapter" data-level="40.6.4" data-path="m13a-hypothesis-testing.html"><a href="m13a-hypothesis-testing.html#additional-resources-3"><i class="fa fa-check"></i><b>40.6.4</b> Additional resources</a></li>
<li class="chapter" data-level="40.6.5" data-path="m13a-hypothesis-testing.html"><a href="m13a-hypothesis-testing.html#whats-to-come-5"><i class="fa fa-check"></i><b>40.6.5</b> What’s to come</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="41" data-path="m13c-explore-hypothesis-testing-with-your-own-data.html"><a href="m13c-explore-hypothesis-testing-with-your-own-data.html"><i class="fa fa-check"></i><b>41</b> M13C: Explore Hypothesis Testing With Your Own Data</a></li>
<li class="chapter" data-level="42" data-path="module-14-understanding.html"><a href="module-14-understanding.html"><i class="fa fa-check"></i><b>42</b> Module 14 Understanding</a></li>
<li class="chapter" data-level="43" data-path="m14a-inferential-regression.html"><a href="m14a-inferential-regression.html"><i class="fa fa-check"></i><b>43</b> M14A: Inferential Regression</a>
<ul>
<li class="chapter" data-level="" data-path="m14a-inferential-regression.html"><a href="m14a-inferential-regression.html#inf-packages"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="43.1" data-path="m14a-inferential-regression.html"><a href="m14a-inferential-regression.html#regression-refresher"><i class="fa fa-check"></i><b>43.1</b> Regression refresher</a>
<ul>
<li class="chapter" data-level="43.1.1" data-path="m14a-inferential-regression.html"><a href="m14a-inferential-regression.html#teaching-evaluations-analysis"><i class="fa fa-check"></i><b>43.1.1</b> Teaching evaluations analysis</a></li>
<li class="chapter" data-level="43.1.2" data-path="m14a-inferential-regression.html"><a href="m14a-inferential-regression.html#sampling-scenario-2"><i class="fa fa-check"></i><b>43.1.2</b> Sampling scenario</a></li>
</ul></li>
<li class="chapter" data-level="43.2" data-path="m14a-inferential-regression.html"><a href="m14a-inferential-regression.html#regression-interp"><i class="fa fa-check"></i><b>43.2</b> Interpreting regression tables</a>
<ul>
<li class="chapter" data-level="43.2.1" data-path="m14a-inferential-regression.html"><a href="m14a-inferential-regression.html#regression-se"><i class="fa fa-check"></i><b>43.2.1</b> Standard error</a></li>
<li class="chapter" data-level="43.2.2" data-path="m14a-inferential-regression.html"><a href="m14a-inferential-regression.html#regression-test-statistic"><i class="fa fa-check"></i><b>43.2.2</b> Test statistic</a></li>
<li class="chapter" data-level="43.2.3" data-path="m14a-inferential-regression.html"><a href="m14a-inferential-regression.html#p-value"><i class="fa fa-check"></i><b>43.2.3</b> p-value</a></li>
<li class="chapter" data-level="43.2.4" data-path="m14a-inferential-regression.html"><a href="m14a-inferential-regression.html#confidence-interval"><i class="fa fa-check"></i><b>43.2.4</b> Confidence interval</a></li>
<li class="chapter" data-level="43.2.5" data-path="m14a-inferential-regression.html"><a href="m14a-inferential-regression.html#regression-table-computation"><i class="fa fa-check"></i><b>43.2.5</b> How does R compute the table?</a></li>
</ul></li>
<li class="chapter" data-level="43.3" data-path="m14a-inferential-regression.html"><a href="m14a-inferential-regression.html#regression-conditions"><i class="fa fa-check"></i><b>43.3</b> Conditions for inference for regression</a>
<ul>
<li class="chapter" data-level="43.3.1" data-path="m14a-inferential-regression.html"><a href="m14a-inferential-regression.html#residuals-refresher"><i class="fa fa-check"></i><b>43.3.1</b> Residuals refresher</a></li>
<li class="chapter" data-level="43.3.2" data-path="m14a-inferential-regression.html"><a href="m14a-inferential-regression.html#linearity-of-relationship"><i class="fa fa-check"></i><b>43.3.2</b> Linearity of relationship</a></li>
<li class="chapter" data-level="43.3.3" data-path="m14a-inferential-regression.html"><a href="m14a-inferential-regression.html#independence-of-residuals"><i class="fa fa-check"></i><b>43.3.3</b> Independence of residuals</a></li>
<li class="chapter" data-level="43.3.4" data-path="m14a-inferential-regression.html"><a href="m14a-inferential-regression.html#normality-of-residuals"><i class="fa fa-check"></i><b>43.3.4</b> Normality of residuals</a></li>
<li class="chapter" data-level="43.3.5" data-path="m14a-inferential-regression.html"><a href="m14a-inferential-regression.html#equality-of-variance"><i class="fa fa-check"></i><b>43.3.5</b> Equality of variance</a></li>
<li class="chapter" data-level="43.3.6" data-path="m14a-inferential-regression.html"><a href="m14a-inferential-regression.html#what-is-the-conclusion"><i class="fa fa-check"></i><b>43.3.6</b> What’s the conclusion?</a></li>
</ul></li>
<li class="chapter" data-level="43.4" data-path="m14a-inferential-regression.html"><a href="m14a-inferential-regression.html#infer-regression"><i class="fa fa-check"></i><b>43.4</b> Simulation-based inference for regression</a>
<ul>
<li class="chapter" data-level="43.4.1" data-path="m14a-inferential-regression.html"><a href="m14a-inferential-regression.html#confidence-interval-for-slope"><i class="fa fa-check"></i><b>43.4.1</b> Confidence interval for slope</a></li>
<li class="chapter" data-level="43.4.2" data-path="m14a-inferential-regression.html"><a href="m14a-inferential-regression.html#hypothesis-test-for-slope"><i class="fa fa-check"></i><b>43.4.2</b> Hypothesis test for slope</a></li>
</ul></li>
<li class="chapter" data-level="43.5" data-path="m14a-inferential-regression.html"><a href="m14a-inferential-regression.html#inference-conclusion"><i class="fa fa-check"></i><b>43.5</b> Conclusion</a>
<ul>
<li class="chapter" data-level="43.5.1" data-path="m14a-inferential-regression.html"><a href="m14a-inferential-regression.html#relating-regression-to-other-methods"><i class="fa fa-check"></i><b>43.5.1</b> Relating regression to other methods</a></li>
<li class="chapter" data-level="43.5.2" data-path="m14a-inferential-regression.html"><a href="m14a-inferential-regression.html#theory-regression"><i class="fa fa-check"></i><b>43.5.2</b> Theory-based inference for regression</a></li>
<li class="chapter" data-level="43.5.3" data-path="m14a-inferential-regression.html"><a href="m14a-inferential-regression.html#summary-of-statistical-inference"><i class="fa fa-check"></i><b>43.5.3</b> Summary of statistical inference</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="44" data-path="m14c-perform-an-inferential-regression-with-your-own-data.html"><a href="m14c-perform-an-inferential-regression-with-your-own-data.html"><i class="fa fa-check"></i><b>44</b> M14C: Perform an Inferential Regression With Your Own Data</a></li>
<li class="chapter" data-level="45" data-path="m15u-reflect-on-your-understanding-of-data-science.html"><a href="m15u-reflect-on-your-understanding-of-data-science.html"><i class="fa fa-check"></i><b>45</b> M15U: Reflect on Your Understanding of Data Science</a></li>
<li class="chapter" data-level="46" data-path="m15a-reflect-on-your-application-of-data-science.html"><a href="m15a-reflect-on-your-application-of-data-science.html"><i class="fa fa-check"></i><b>46</b> M15A: Reflect on Your Application of Data Science</a></li>
<li class="chapter" data-level="47" data-path="m15c-reflect-on-your-connection-of-data-science.html"><a href="m15c-reflect-on-your-connection-of-data-science.html"><i class="fa fa-check"></i><b>47</b> M15C: Reflect on Your Connection of Data Science</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introduction to Data Science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data-visualization" class="section level1 hasAnchor" number="22">
<h1><span class="header-section-number">22</span> Data Visualization<a href="data-visualization.html#data-visualization" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>We begin the development of your data science toolbox with data visualization. By visualizing data, we gain valuable insights we couldn’t initially obtain from just looking at the raw data values. We’ll use the <code>ggplot2</code> package, as it provides an easy way to customize your plots. <code>ggplot2</code> is rooted in the data visualization theory known as <em>the grammar of graphics</em> <span class="citation">[@wilkinson2005]</span>, developed by Leland Wilkinson. </p>
<p>At their most basic, graphics/plots/charts (we use these terms interchangeably in this book) provide a nice way to explore the patterns in data, such as the presence of <em>outliers</em>, <em>distributions</em> of individual variables, and <em>relationships</em> between groups of variables. Graphics are designed to emphasize the findings and insights you want your audience to understand. This does, however, require a balancing act. On the one hand, you want to highlight as many interesting findings as possible. On the other hand, you don’t want to include so much information that it overwhelms your audience.</p>
<p>As we will see, plots also help us to identify patterns and outliers in our data. We’ll see that a common extension of these ideas is to compare the <em>distribution</em> of one numerical variable, such as what are the center and spread of the values, as we go across the levels of a different categorical variable.</p>
<div id="needed-packages" class="section level3 unnumbered hasAnchor">
<h3>Needed packages<a href="data-visualization.html#needed-packages" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s load all the packages needed for this chapter (this assumes you’ve already installed them). Read Section <a href="getting-started.html#packages">6.4</a> for information on how to install and load R packages.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="data-visualization.html#cb1-1" tabindex="-1"></a><span class="fu">library</span>(nycflights13)</span>
<span id="cb1-2"><a href="data-visualization.html#cb1-2" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="data-visualization.html#cb1-3" tabindex="-1"></a><span class="fu">library</span>(moderndive)</span></code></pre></div>
</div>
<div id="grammarofgraphics" class="section level2 hasAnchor" number="22.1">
<h2><span class="header-section-number">22.1</span> The grammar of graphics<a href="data-visualization.html#grammarofgraphics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We start with a discussion of a theoretical framework for data visualization known as “the grammar of graphics.” This framework serves as the foundation for the <code>ggplot2</code> package which we’ll use extensively in this chapter. Think of how we construct and form sentences in English by combining different elements, like nouns, verbs, articles, subjects, objects, etc. We can’t just combine these elements in any arbitrary order; we must do so following a set of rules known as a linguistic grammar. Similarly to a linguistic grammar, “the grammar of graphics” defines a set of rules for constructing <em>statistical graphics</em> by combining different types of <em>layers</em>. This grammar was created by Leland Wilkinson <span class="citation">[@wilkinson2005]</span> and has been implemented in a variety of data visualization software platforms like R, but also <a href="https://plot.ly/">Plotly</a> and <a href="https://www.tableau.com/">Tableau</a>.</p>
<div id="components-of-the-grammar" class="section level3 hasAnchor" number="22.1.1">
<h3><span class="header-section-number">22.1.1</span> Components of the grammar<a href="data-visualization.html#components-of-the-grammar" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In short, the grammar tells us that:</p>
<blockquote>
<p><strong>A statistical graphic is a <code>mapping</code> of <code>data</code> variables to <code>aes</code>thetic attributes of <code>geom</code>etric objects.</strong></p>
</blockquote>
<p>Specifically, we can break a graphic into the following three essential components:</p>
<ol style="list-style-type: decimal">
<li><code>data</code>: the dataset containing the variables of interest.</li>
<li><code>geom</code>: the geometric object in question. This refers to the type of object we can observe in a plot. For example: points, lines, and bars.</li>
<li><code>aes</code>: aesthetic attributes of the geometric object. For example, x/y position, color, shape, and size. Aesthetic attributes are <em>mapped</em> to variables in the dataset.</li>
</ol>
<p>You might be wondering why we wrote the terms <code>data</code>, <code>geom</code>, and <code>aes</code> in a computer code type font. We’ll see very shortly that we’ll specify the elements of the grammar in R using these terms. However, let’s first break down the grammar with an example.</p>
</div>
<div id="gapminder" class="section level3 hasAnchor" number="22.1.2">
<h3><span class="header-section-number">22.1.2</span> Gapminder data<a href="data-visualization.html#gapminder" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In February 2006, a Swedish physician and data advocate named Hans Rosling gave a TED talk titled <a href="https://www.ted.com/talks/hans_rosling_shows_the_best_stats_you_ve_ever_seen">“The best stats you’ve ever seen”</a> where he presented global economic, health, and development data from the website <a href="http://www.gapminder.org/tools/#_locale_id=en;&amp;chart-type=bubbles">gapminder.org</a>. For example, for data on 142 countries in 2007, let’s consider only a few countries in Table <a href="data-visualization.html#tab:gapminder-2007">22.1</a> as a peek into the data.</p>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:gapminder-2007">Table 22.1: </span>Gapminder 2007 Data: First 3 of 142 countries
</caption>
<thead>
<tr>
<th style="text-align:left;">
Country
</th>
<th style="text-align:left;">
Continent
</th>
<th style="text-align:right;">
Life Expectancy
</th>
<th style="text-align:right;">
Population
</th>
<th style="text-align:right;">
GDP per Capita
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Afghanistan
</td>
<td style="text-align:left;">
Asia
</td>
<td style="text-align:right;">
43.8
</td>
<td style="text-align:right;">
31889923
</td>
<td style="text-align:right;">
975
</td>
</tr>
<tr>
<td style="text-align:left;">
Albania
</td>
<td style="text-align:left;">
Europe
</td>
<td style="text-align:right;">
76.4
</td>
<td style="text-align:right;">
3600523
</td>
<td style="text-align:right;">
5937
</td>
</tr>
<tr>
<td style="text-align:left;">
Algeria
</td>
<td style="text-align:left;">
Africa
</td>
<td style="text-align:right;">
72.3
</td>
<td style="text-align:right;">
33333216
</td>
<td style="text-align:right;">
6223
</td>
</tr>
</tbody>
</table>
<p>Each row in this table corresponds to a country in 2007. For each row, we have 5 columns:</p>
<ol style="list-style-type: decimal">
<li><strong>Country</strong>: Name of country.</li>
<li><strong>Continent</strong>: Which of the five continents the country is part of. Note that “Americas” includes countries in both North and South America and that Antarctica is excluded.</li>
<li><strong>Life Expectancy</strong>: Life expectancy in years.</li>
<li><strong>Population</strong>: Number of people living in the country.</li>
<li><strong>GDP per Capita</strong>: Gross domestic product (in US dollars).</li>
</ol>
<p>Now consider Figure <a href="data-visualization.html#fig:gapminder">22.1</a>, which plots this for all 142 of the data’s countries.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:gapminder"></span>
<img src="_main_files/figure-html/gapminder-1.png" alt="Life expectancy over GDP per capita in 2007." width="\textwidth" />
<p class="caption">
Figure 22.1: Life expectancy over GDP per capita in 2007.
</p>
</div>
<p>Let’s view this plot through the grammar of graphics:</p>
<ol style="list-style-type: decimal">
<li>The <code>data</code> variable <strong>GDP per Capita</strong> gets mapped to the <code>x</code>-position <code>aes</code>thetic of the points.</li>
<li>The <code>data</code> variable <strong>Life Expectancy</strong> gets mapped to the <code>y</code>-position <code>aes</code>thetic of the points.</li>
<li>The <code>data</code> variable <strong>Population</strong> gets mapped to the <code>size</code> <code>aes</code>thetic of the points.</li>
<li>The <code>data</code> variable <strong>Continent</strong> gets mapped to the <code>color</code> <code>aes</code>thetic of the points.</li>
</ol>
<p>We’ll see shortly that <code>data</code> corresponds to the particular data frame where our data is saved and that “data variables” correspond to particular columns in the data frame. Furthermore, the type of <code>geom</code>etric object considered in this plot are points. That being said, while in this example we are considering points, graphics are not limited to just points. We can also use lines, bars, and other geometric objects.</p>
<p>Let’s summarize the three essential components of the grammar in Table <a href="data-visualization.html#tab:summary-table-gapminder">22.2</a>.</p>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:summary-table-gapminder">Table 22.2: </span>Summary of the grammar of graphics for this plot
</caption>
<thead>
<tr>
<th style="text-align:left;">
data variable
</th>
<th style="text-align:left;">
aes
</th>
<th style="text-align:left;">
geom
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
GDP per Capita
</td>
<td style="text-align:left;">
x
</td>
<td style="text-align:left;">
point
</td>
</tr>
<tr>
<td style="text-align:left;">
Life Expectancy
</td>
<td style="text-align:left;">
y
</td>
<td style="text-align:left;">
point
</td>
</tr>
<tr>
<td style="text-align:left;">
Population
</td>
<td style="text-align:left;">
size
</td>
<td style="text-align:left;">
point
</td>
</tr>
<tr>
<td style="text-align:left;">
Continent
</td>
<td style="text-align:left;">
color
</td>
<td style="text-align:left;">
point
</td>
</tr>
</tbody>
</table>
</div>
<div id="other-components" class="section level3 hasAnchor" number="22.1.3">
<h3><span class="header-section-number">22.1.3</span> Other components<a href="data-visualization.html#other-components" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>There are other components of the grammar of graphics we can control as well. As you start to delve deeper into the grammar of graphics, you’ll start to encounter these topics more frequently. In this book, we’ll keep things simple and only work with these two additional components:</p>
<ul>
<li><code>facet</code>ing breaks up a plot into several plots split by the values of another variable (Section <a href="data-visualization.html#facets">22.6</a>) </li>
<li><code>position</code> adjustments for barplots (Section <a href="data-visualization.html#geombar">22.8</a>) </li>
</ul>
<p>Other more complex components like <code>scales</code> and <code>coord</code>inate systems are left for a more advanced text such as <a href="http://r4ds.had.co.nz/data-visualisation.html#aesthetic-mappings"><em>R for Data Science</em></a> <span class="citation">[@rds2016]</span>. Generally speaking, the grammar of graphics allows for a high degree of customization of plots and also a consistent framework for easily updating and modifying them.</p>
</div>
<div id="ggplot2-package" class="section level3 hasAnchor" number="22.1.4">
<h3><span class="header-section-number">22.1.4</span> ggplot2 package<a href="data-visualization.html#ggplot2-package" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In this book, we will use the <code>ggplot2</code> package for data visualization, which is an implementation of the <code>g</code>rammar of <code>g</code>raphics for R <span class="citation">[@R-ggplot2]</span>. As we noted earlier, a lot of the previous section was written in a computer code type font. This is because the various components of the grammar of graphics are specified in the <code>ggplot()</code> function included in the <code>ggplot2</code> package. For the purposes of this book, we’ll always provide the <code>ggplot()</code> function with the following arguments (i.e., inputs) at a minimum:</p>
<ul>
<li>The data frame where the variables exist: the <code>data</code> argument.</li>
<li>The mapping of the variables to aesthetic attributes: the <code>mapping</code> argument which specifies the <code>aes</code>thetic attributes involved.</li>
</ul>
<p>After we’ve specified these components, we then add <em>layers</em> to the plot using the <code>+</code> sign. The most essential layer to add to a plot is the layer that specifies which type of <code>geom</code>etric object we want the plot to involve: points, lines, bars, and others. Other layers we can add to a plot include the plot title, axes labels, visual themes for the plots, and facets (which we’ll see in Section <a href="data-visualization.html#facets">22.6</a>).</p>
<p>Let’s now put the theory of the grammar of graphics into practice.</p>
</div>
</div>
<div id="FiveNG" class="section level2 hasAnchor" number="22.2">
<h2><span class="header-section-number">22.2</span> Five named graphs - the 5NG<a href="data-visualization.html#FiveNG" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In order to keep things simple in this book, we will only focus on five different types of graphics, each with a commonly given name. We term these “five named graphs” or in abbreviated form, the <strong>5NG</strong>: </p>
<ol style="list-style-type: decimal">
<li>scatterplots</li>
<li>linegraphs</li>
<li>histograms</li>
<li>boxplots</li>
<li>barplots</li>
</ol>
<p>We’ll also present some variations of these plots, but with this basic repertoire of five graphics in your toolbox, you can visualize a wide array of different variable types. Note that certain plots are only appropriate for categorical variables, while others are only appropriate for numerical variables.</p>
</div>
<div id="scatterplots" class="section level2 hasAnchor" number="22.3">
<h2><span class="header-section-number">22.3</span> 5NG#1: Scatterplots<a href="data-visualization.html#scatterplots" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The simplest of the 5NG are <em>scatterplots</em>, also called <em>bivariate plots</em>. They allow you to visualize the <em>relationship</em> between two numerical variables. While you may already be familiar with scatterplots, let’s view them through the lens of the grammar of graphics we presented in Section <a href="data-visualization.html#grammarofgraphics">22.1</a>. Specifically, we will visualize the relationship between the following two numerical variables in the <code>alaska_flights</code> data frame included in the <code>moderndive</code> package:</p>
<ol style="list-style-type: decimal">
<li><code>dep_delay</code>: departure delay on the horizontal “x” axis and</li>
<li><code>arr_delay</code>: arrival delay on the vertical “y” axis</li>
</ol>
<p>for Alaska Airlines flights leaving NYC in 2013. In other words, <code>alaska_flights</code> does not consist of <em>all</em> flights that left NYC in 2013, but rather only those flights where <code>carrier</code> is <code>AS</code> (which is Alaska Airlines’ carrier code).</p>
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC2.1)</strong> Take a look at both the <code>flights</code> data frame from the <code>nycflights13</code> package and the <code>alaska_flights</code> data frame from the <code>moderndive</code> package by running <code>View(flights)</code> and <code>View(alaska_flights)</code>. In what respect do these data frames differ? For example, think about the number of rows in each dataset.</p>
<div class="learncheck">

</div>
<div id="geompoint" class="section level3 hasAnchor" number="22.3.1">
<h3><span class="header-section-number">22.3.1</span> Scatterplots via <code>geom_point</code><a href="data-visualization.html#geompoint" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s now go over the code that will create the desired scatterplot, while keeping in mind the grammar of graphics framework we introduced in Section <a href="data-visualization.html#grammarofgraphics">22.1</a>. Let’s take a look at the code and break it down piece-by-piece.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="data-visualization.html#cb2-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> alaska_flights, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> dep_delay, <span class="at">y =</span> arr_delay)) <span class="sc">+</span> </span>
<span id="cb2-2"><a href="data-visualization.html#cb2-2" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<p>Within the <code>ggplot()</code> function, we specify two of the components of the grammar of graphics as arguments (i.e., inputs):</p>
<ol style="list-style-type: decimal">
<li>The <code>data</code> as the <code>alaska_flights</code> data frame via <code>data = alaska_flights</code>.</li>
<li>The <code>aes</code>thetic <code>mapping</code> by setting <code>mapping = aes(x = dep_delay, y = arr_delay)</code>. Specifically, the variable <code>dep_delay</code> maps to the <code>x</code> position aesthetic, while the variable <code>arr_delay</code> maps to the <code>y</code> position.</li>
</ol>
<p>We then add a layer to the <code>ggplot()</code> function call using the <code>+</code> sign. The added layer in question specifies the third component of the grammar: the <code>geom</code>etric object. In this case, the geometric object is set to be points by specifying <code>geom_point()</code>. After running these two lines of code in your console, you’ll notice two outputs: a warning message and the graphic shown in Figure <a href="data-visualization.html#fig:noalpha">22.2</a>.</p>
<pre><code>## Warning: Removed 5 rows containing missing values (geom_point).</code></pre>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:noalpha"></span>
<img src="_main_files/figure-html/noalpha-1.png" alt="Arrival delays versus departure delays for Alaska Airlines flights from NYC in 2013." width="\textwidth" />
<p class="caption">
Figure 22.2: Arrival delays versus departure delays for Alaska Airlines flights from NYC in 2013.
</p>
</div>
<p>Let’s first unpack the graphic in Figure <a href="data-visualization.html#fig:noalpha">22.2</a>. Observe that a <em>positive relationship</em> exists between <code>dep_delay</code> and <code>arr_delay</code>: as departure delays increase, arrival delays tend to also increase. Observe also the large mass of points clustered near (0, 0), the point indicating flights that neither departed nor arrived late.</p>
<p>Let’s turn our attention to the warning message. R is alerting us to the fact that five rows were ignored due to them being missing. For these 5 rows, either the value for <code>dep_delay</code> or <code>arr_delay</code> or both were missing (recorded in R as <code>NA</code>), and thus these rows were ignored in our plot.</p>
<p>Before we continue, let’s make a few more observations about this code that created the scatterplot. Note that the <code>+</code> sign comes at the end of lines, and not at the beginning. You’ll get an error in R if you put it at the beginning of a line. When adding layers to a plot, you are encouraged to start a new line after the <code>+</code> (by pressing the Return/Enter button on your keyboard) so that the code for each layer is on a new line. As we add more and more layers to plots, you’ll see this will greatly improve the legibility of your code.</p>
<p>To stress the importance of adding the layer specifying the <code>geom</code>etric object, consider Figure <a href="data-visualization.html#fig:nolayers">22.3</a> where no layers are added. Because the <code>geom</code>etric object was not specified, we have a blank plot which is not very useful!</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="data-visualization.html#cb4-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> alaska_flights, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> dep_delay, <span class="at">y =</span> arr_delay))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:nolayers"></span>
<img src="_main_files/figure-html/nolayers-1.png" alt="A plot with no layers." width="\textwidth" />
<p class="caption">
Figure 22.3: A plot with no layers.
</p>
</div>
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC2.2)</strong> What are some practical reasons why <code>dep_delay</code> and <code>arr_delay</code> have a positive relationship?</p>
<p><strong>(LC2.3)</strong> What variables in the <code>weather</code> data frame would you expect to have a negative correlation (i.e., a negative relationship) with <code>dep_delay</code>? Why? Remember that we are focusing on numerical variables here. Hint: Explore the <code>weather</code> dataset by using the <code>View()</code> function.</p>
<p><strong>(LC2.4)</strong> Why do you believe there is a cluster of points near (0, 0)? What does (0, 0) correspond to in terms of the Alaska Air flights?</p>
<p><strong>(LC2.5)</strong> What are some other features of the plot that stand out to you?</p>
<p><strong>(LC2.6)</strong> Create a new scatterplot using different variables in the <code>alaska_flights</code> data frame by modifying the example given.</p>
<div class="learncheck">

</div>
</div>
<div id="overplotting" class="section level3 hasAnchor" number="22.3.2">
<h3><span class="header-section-number">22.3.2</span> Overplotting<a href="data-visualization.html#overplotting" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The large mass of points near (0, 0) in Figure <a href="data-visualization.html#fig:noalpha">22.2</a> can cause some confusion since it is hard to tell the true number of points that are plotted. This is the result of a phenomenon called <em>overplotting</em>. As one may guess, this corresponds to points being plotted on top of each other over and over again. When overplotting occurs, it is difficult to know the number of points being plotted. There are two methods to address the issue of overplotting. Either by</p>
<ol style="list-style-type: decimal">
<li>Adjusting the transparency of the points or</li>
<li>Adding a little random “jitter”, or random “nudges”, to each of the points.</li>
</ol>
<p><strong>Method 1: Changing the transparency</strong></p>
<p>The first way of addressing overplotting is to change the transparency/opacity of the points by setting the <code>alpha</code> argument in <code>geom_point()</code>. We can change the <code>alpha</code> argument to be any value between <code>0</code> and <code>1</code>, where <code>0</code> sets the points to be 100% transparent and <code>1</code> sets the points to be 100% opaque. By default, <code>alpha</code> is set to <code>1</code>. In other words, if we don’t explicitly set an <code>alpha</code> value, R will use <code>alpha = 1</code>.</p>
<p>Note how the following code is identical to the code in Section <a href="data-visualization.html#scatterplots">22.3</a> that created the scatterplot with overplotting, but with <code>alpha = 0.2</code> added to the <code>geom_point()</code> function:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="data-visualization.html#cb5-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> alaska_flights, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> dep_delay, <span class="at">y =</span> arr_delay)) <span class="sc">+</span> </span>
<span id="cb5-2"><a href="data-visualization.html#cb5-2" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:alpha"></span>
<img src="_main_files/figure-html/alpha-1.png" alt="Arrival vs. departure delays scatterplot with alpha = 0.2." width="\textwidth" />
<p class="caption">
Figure 22.4: Arrival vs. departure delays scatterplot with alpha = 0.2.
</p>
</div>
<p>The key feature to note in Figure <a href="data-visualization.html#fig:alpha">22.4</a> is that the transparency of the points is cumulative: areas with a high-degree of overplotting are darker, whereas areas with a lower degree are less dark. Note furthermore that there is no <code>aes()</code> surrounding <code>alpha = 0.2</code>. This is because we are not mapping a variable to an aesthetic attribute, but rather merely changing the default setting of <code>alpha</code>. In fact, you’ll receive an error if you try to change the second line to read <code>geom_point(aes(alpha = 0.2))</code>.</p>
<p><strong>Method 2: Jittering the points</strong></p>
<p>The second way of addressing overplotting is by <em>jittering</em> all the points. This means giving each point a small “nudge” in a random direction. You can think of “jittering” as shaking the points around a bit on the plot. Let’s illustrate using a simple example first. Say we have a data frame with 4 identical rows of x and y values: (0,0), (0,0), (0,0), and (0,0). In Figure <a href="data-visualization.html#fig:jitter-example-plot-1">22.5</a>, we present both the regular scatterplot of these 4 points (on the left) and its jittered counterpart (on the right).</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:jitter-example-plot-1"></span>
<img src="_main_files/figure-html/jitter-example-plot-1-1.png" alt="Regular and jittered scatterplot." width="\textwidth" />
<p class="caption">
Figure 22.5: Regular and jittered scatterplot.
</p>
</div>
<p>In the left-hand regular scatterplot, observe that the 4 points are superimposed on top of each other. While we know there are 4 values being plotted, this fact might not be apparent to others. In the right-hand jittered scatterplot, it is now plainly evident that this plot involves four points since each point is given a random “nudge.”</p>
<p>Keep in mind, however, that jittering is strictly a visualization tool; even after creating a jittered scatterplot, the original values saved in the data frame remain unchanged. </p>
<p>To create a jittered scatterplot, instead of using <code>geom_point()</code>, we use <code>geom_jitter()</code>. Observe how the following code is very similar to the code that created the scatterplot with overplotting in Subsection <a href="data-visualization.html#geompoint">22.3.1</a>, but with <code>geom_point()</code> replaced with <code>geom_jitter()</code>.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="data-visualization.html#cb6-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> alaska_flights, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> dep_delay, <span class="at">y =</span> arr_delay)) <span class="sc">+</span> </span>
<span id="cb6-2"><a href="data-visualization.html#cb6-2" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="dv">30</span>, <span class="at">height =</span> <span class="dv">30</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:jitter"></span>
<img src="_main_files/figure-html/jitter-1.png" alt="Arrival versus departure delays jittered scatterplot." width="\textwidth" />
<p class="caption">
Figure 22.6: Arrival versus departure delays jittered scatterplot.
</p>
</div>
<p>In order to specify how much jitter to add, we adjusted the <code>width</code> and <code>height</code> arguments to <code>geom_jitter()</code>. This corresponds to how hard you’d like to shake the plot in horizontal x-axis units and vertical y-axis units, respectively. In this case, both axes are in minutes. How much jitter should we add using the <code>width</code> and <code>height</code> arguments? On the one hand, it is important to add just enough jitter to break any overlap in points, but on the other hand, not so much that we completely alter the original pattern in points.</p>
<p>As can be seen in the resulting Figure <a href="data-visualization.html#fig:jitter">22.6</a>, in this case jittering doesn’t really provide much new insight. In this particular case, it can be argued that changing the transparency of the points by setting <code>alpha</code> proved more effective. When would it be better to use a jittered scatterplot? When would it be better to alter the points’ transparency? There is no single right answer that applies to all situations. You need to make a subjective choice and own that choice. At the very least when confronted with overplotting, however, we suggest you make both types of plots and see which one better emphasizes the point you are trying to make.</p>
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC2.7)</strong> Why is setting the <code>alpha</code> argument value useful with scatterplots? What further information does it give you that a regular scatterplot cannot?</p>
<p><strong>(LC2.8)</strong> After viewing Figure <a href="data-visualization.html#fig:alpha">22.4</a>, give an approximate range of arrival delays and departure delays that occur most frequently. How has that region changed compared to when you observed the same plot without <code>alpha = 0.2</code> set in Figure <a href="data-visualization.html#fig:noalpha">22.2</a>?</p>
<div class="learncheck">

</div>
</div>
<div id="summary" class="section level3 hasAnchor" number="22.3.3">
<h3><span class="header-section-number">22.3.3</span> Summary<a href="data-visualization.html#summary" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Scatterplots display the relationship between two numerical variables. They are among the most commonly used plots because they can provide an immediate way to see the trend in one numerical variable versus another. However, if you try to create a scatterplot where either one of the two variables is not numerical, you might get strange results. Be careful!</p>
<p>With medium to large datasets, you may need to play around with the different modifications to scatterplots we saw such as changing the transparency/opacity of the points or by jittering the points. This tweaking is often a fun part of data visualization, since you’ll have the chance to see different relationships emerge as you tinker with your plots.</p>
</div>
</div>
<div id="linegraphs" class="section level2 hasAnchor" number="22.4">
<h2><span class="header-section-number">22.4</span> 5NG#2: Linegraphs<a href="data-visualization.html#linegraphs" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The next of the five named graphs are linegraphs. Linegraphs show the relationship between two numerical variables when the variable on the x-axis, also called the <em>explanatory</em> variable, is of a sequential nature. In other words, there is an inherent ordering to the variable.</p>
<p>The most common examples of linegraphs have some notion of time on the x-axis: hours, days, weeks, years, etc. Since time is sequential, we connect consecutive observations of the variable on the y-axis with a line. Linegraphs that have some notion of time on the x-axis are also called <em>time series</em> plots. Let’s illustrate linegraphs using another dataset in the <code>nycflights13</code> package: the <code>weather</code> data frame.</p>
<p>Let’s explore the <code>weather</code> data frame from the <code>nycflights13</code> package by running <code>View(weather)</code> and <code>glimpse(weather)</code>. Furthermore let’s read the associated help file by running <code>?weather</code> to bring up the help file.</p>
<p>Observe that there is a variable called <code>temp</code> of hourly temperature recordings in Fahrenheit at weather stations near all three major airports in New York City: Newark (<code>origin</code> code <code>EWR</code>), John F. Kennedy International (<code>JFK</code>), and LaGuardia (<code>LGA</code>).</p>
<p>However, instead of considering hourly temperatures for all days in 2013 for all three airports, for simplicity let’s only consider hourly temperatures at Newark airport for the first 15 days in January. This data is accessible in the <code>early_january_weather</code> data frame included in the <code>moderndive</code> package. In other words, <code>early_january_weather</code> contains hourly weather observations for <code>origin</code> equal to <code>EWR</code> (Newark’s airport code), <code>month</code> equal to <code>1</code>, and <code>day</code> less than or equal to <code>15</code>.</p>
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC2.9)</strong> Take a look at both the <code>weather</code> data frame from the <code>nycflights13</code> package and the <code>early_january_weather</code> data frame from the <code>moderndive</code> package by running <code>View(weather)</code> and <code>View(early_january_weather)</code>. In what respect do these data frames differ?</p>
<p><strong>(LC2.10)</strong> <code>View()</code> the <code>flights</code> data frame again. Why does the <code>time_hour</code> variable uniquely identify the hour of the measurement, whereas the <code>hour</code> variable does not?</p>
<div class="learncheck">

</div>
<div id="geomline" class="section level3 hasAnchor" number="22.4.1">
<h3><span class="header-section-number">22.4.1</span> Linegraphs via <code>geom_line</code><a href="data-visualization.html#geomline" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s create a time series plot of the hourly temperatures saved in the <code>early_january_weather</code> data frame by using <code>geom_line()</code> to create a linegraph, instead of using <code>geom_point()</code> like we used previously to create scatterplots:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="data-visualization.html#cb7-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> early_january_weather, </span>
<span id="cb7-2"><a href="data-visualization.html#cb7-2" tabindex="-1"></a>       <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> time_hour, <span class="at">y =</span> temp)) <span class="sc">+</span></span>
<span id="cb7-3"><a href="data-visualization.html#cb7-3" tabindex="-1"></a>  <span class="fu">geom_line</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:hourlytemp"></span>
<img src="_main_files/figure-html/hourlytemp-1.png" alt="Hourly temperature in Newark for January 1-15, 2013." width="\textwidth" />
<p class="caption">
Figure 22.7: Hourly temperature in Newark for January 1-15, 2013.
</p>
</div>
<p>Much as with the <code>ggplot()</code> code that created the scatterplot of departure and arrival delays for Alaska Airlines flights in Figure <a href="data-visualization.html#fig:noalpha">22.2</a>, let’s break down this code piece-by-piece in terms of the grammar of graphics:</p>
<p>Within the <code>ggplot()</code> function call, we specify two of the components of the grammar of graphics as arguments:</p>
<ol style="list-style-type: decimal">
<li>The <code>data</code> to be the <code>early_january_weather</code> data frame by setting <code>data = early_january_weather</code>.</li>
<li>The <code>aes</code>thetic <code>mapping</code> by setting <code>mapping = aes(x = time_hour, y = temp)</code>. Specifically, the variable <code>time_hour</code> maps to the <code>x</code> position aesthetic, while the variable <code>temp</code> maps to the <code>y</code> position aesthetic.</li>
</ol>
<p>We add a layer to the <code>ggplot()</code> function call using the <code>+</code> sign. The layer in question specifies the third component of the grammar: the <code>geom</code>etric object in question. In this case, the geometric object is a <code>line</code> set by specifying <code>geom_line()</code>.</p>
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC2.11)</strong> Why should linegraphs be avoided when there is not a clear ordering of the horizontal axis?</p>
<p><strong>(LC2.12)</strong> Why are linegraphs frequently used when time is the explanatory variable on the x-axis?</p>
<p><strong>(LC2.13)</strong> Plot a time series of a variable other than <code>temp</code> for Newark Airport in the first 15 days of January 2013.</p>
<div class="learncheck">

</div>
</div>
<div id="summary-1" class="section level3 hasAnchor" number="22.4.2">
<h3><span class="header-section-number">22.4.2</span> Summary<a href="data-visualization.html#summary-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Linegraphs, just like scatterplots, display the relationship between two numerical variables. However, it is preferred to use linegraphs over scatterplots when the variable on the x-axis (i.e., the explanatory variable) has an inherent ordering, such as some notion of time.</p>
</div>
</div>
<div id="histograms" class="section level2 hasAnchor" number="22.5">
<h2><span class="header-section-number">22.5</span> 5NG#3: Histograms<a href="data-visualization.html#histograms" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s consider the <code>temp</code> variable in the <code>weather</code> data frame once again, but unlike with the linegraphs in Section <a href="data-visualization.html#linegraphs">22.4</a>, let’s say we don’t care about its relationship with time, but rather we only care about how the values of <code>temp</code> <em>distribute</em>. In other words:</p>
<ol style="list-style-type: decimal">
<li>What are the smallest and largest values?</li>
<li>What is the “center” or “most typical” value?</li>
<li>How do the values spread out?</li>
<li>What are frequent and infrequent values?</li>
</ol>
<p>One way to visualize this <em>distribution</em> of this single variable <code>temp</code> is to plot them on a horizontal line as we do in Figure <a href="data-visualization.html#fig:temp-on-line">22.8</a>:</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:temp-on-line"></span>
<img src="_main_files/figure-html/temp-on-line-1.png" alt="Plot of hourly temperature recordings from NYC in 2013." width="\textwidth" />
<p class="caption">
Figure 22.8: Plot of hourly temperature recordings from NYC in 2013.
</p>
</div>
<p>This gives us a general idea of how the values of <code>temp</code> distribute: observe that temperatures vary from around 11°F (-11°C) up to 100°F (38°C). Furthermore, there appear to be more recorded temperatures between 40°F and 60°F than outside this range. However, because of the high degree of overplotting in the points, it’s hard to get a sense of exactly how many values are between say 50°F and 55°F.</p>
<p>What is commonly produced instead of Figure <a href="data-visualization.html#fig:temp-on-line">22.8</a> is known as a <em>histogram</em>. A histogram is a plot that visualizes the <em>distribution</em> of a numerical value as follows:</p>
<ol style="list-style-type: decimal">
<li>We first cut up the x-axis into a series of <em>bins</em>, where each bin represents a range of values.</li>
<li>For each bin, we count the number of observations that fall in the range corresponding to that bin.</li>
<li>Then for each bin, we draw a bar whose height marks the corresponding count.</li>
</ol>
<p>Let’s drill-down on an example of a histogram, shown in Figure <a href="data-visualization.html#fig:histogramexample">22.9</a>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:histogramexample"></span>
<img src="_main_files/figure-html/histogramexample-1.png" alt="Example histogram." width="\textwidth" />
<p class="caption">
Figure 22.9: Example histogram.
</p>
</div>
<p>Let’s focus only on temperatures between 30°F (-1°C) and 60°F (15°C) for now. Observe that there are three bins of equal width between 30°F and 60°F. Thus we have three bins of width 10°F each: one bin for the 30-40°F range, another bin for the 40-50°F range, and another bin for the 50-60°F range. Since:</p>
<ol style="list-style-type: decimal">
<li>The bin for the 30-40°F range has a height of around 5000. In other words, around 5000 of the hourly temperature recordings are between 30°F and 40°F.</li>
<li>The bin for the 40-50°F range has a height of around 4300. In other words, around 4300 of the hourly temperature recordings are between 40°F and 50°F.</li>
<li>The bin for the 50-60°F range has a height of around 3500. In other words, around 3500 of the hourly temperature recordings are between 50°F and 60°F.</li>
</ol>
<p>All nine bins spanning 10°F to 100°F on the x-axis have this interpretation.</p>
<div id="geomhistogram" class="section level3 hasAnchor" number="22.5.1">
<h3><span class="header-section-number">22.5.1</span> Histograms via <code>geom_histogram</code><a href="data-visualization.html#geomhistogram" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s now present the <code>ggplot()</code> code to plot your first histogram! Unlike with scatterplots and linegraphs, there is now only one variable being mapped in <code>aes()</code>: the single numerical variable <code>temp</code>. The y-aesthetic of a histogram, the count of the observations in each bin, gets computed for you automatically. Furthermore, the geometric object layer is now a <code>geom_histogram()</code>. After running the following code, you’ll see the histogram in Figure <a href="data-visualization.html#fig:weather-histogram">22.10</a> as well as warning messages. We’ll discuss the warning messages first.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="data-visualization.html#cb8-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> weather, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> temp)) <span class="sc">+</span></span>
<span id="cb8-2"><a href="data-visualization.html#cb8-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()</span></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<pre><code>## Warning: Removed 1 rows containing non-finite values (stat_bin).</code></pre>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:weather-histogram"></span>
<img src="_main_files/figure-html/weather-histogram-1.png" alt="Histogram of hourly temperatures at three NYC airports." width="\textwidth" />
<p class="caption">
Figure 22.10: Histogram of hourly temperatures at three NYC airports.
</p>
</div>
<p>The first message is telling us that the histogram was constructed using <code>bins = 30</code> for 30 equally spaced bins. This is known in computer programming as a default value; unless you override this default number of bins with a number you specify, R will choose 30 by default. We’ll see in the next section how to change the number of bins to another value than the default.</p>
<p>The second message is telling us something similar to the warning message we received when we ran the code to create a scatterplot of departure and arrival delays for Alaska Airlines flights in Figure <a href="data-visualization.html#fig:noalpha">22.2</a>: that because one row has a missing <code>NA</code> value for <code>temp</code>, it was omitted from the histogram. R is just giving us a friendly heads up that this was the case.</p>
<p>Now let’s unpack the resulting histogram in Figure <a href="data-visualization.html#fig:weather-histogram">22.10</a>. Observe that values less than 25°F as well as values above 80°F are rather rare. However, because of the large number of bins, it’s hard to get a sense for which range of temperatures is spanned by each bin; everything is one giant amorphous blob. So let’s add white vertical borders demarcating the bins by adding a <code>color = "white"</code> argument to <code>geom_histogram()</code> and ignore the warning about setting the number of bins to a better value:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="data-visualization.html#cb11-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> weather, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> temp)) <span class="sc">+</span></span>
<span id="cb11-2"><a href="data-visualization.html#cb11-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">color =</span> <span class="st">&quot;white&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:weather-histogram-2"></span>
<img src="_main_files/figure-html/weather-histogram-2-1.png" alt="Histogram of hourly temperatures at three NYC airports with white borders." width="\textwidth" />
<p class="caption">
Figure 22.11: Histogram of hourly temperatures at three NYC airports with white borders.
</p>
</div>
<p>We now have an easier time associating ranges of temperatures to each of the bins in Figure <a href="data-visualization.html#fig:weather-histogram-2">22.11</a>. We can also vary the color of the bars by setting the <code>fill</code> argument. For example, you can set the bin colors to be “blue steel” by setting <code>fill = "steelblue"</code>:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="data-visualization.html#cb12-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> weather, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> temp)) <span class="sc">+</span></span>
<span id="cb12-2"><a href="data-visualization.html#cb12-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">color =</span> <span class="st">&quot;white&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;steelblue&quot;</span>)</span></code></pre></div>
<p>If you’re curious, run <code>colors()</code> to see all 657 possible choice of colors in R!</p>
</div>
<div id="adjustbins" class="section level3 hasAnchor" number="22.5.2">
<h3><span class="header-section-number">22.5.2</span> Adjusting the bins<a href="data-visualization.html#adjustbins" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Observe in Figure <a href="data-visualization.html#fig:weather-histogram-2">22.11</a> that in the 50-75°F range there appear to be roughly 8 bins. Thus each bin has width 25 divided by 8, or 3.125°F, which is not a very easily interpretable range to work with. Let’s improve this by adjusting the number of bins in our histogram in one of two ways:</p>
<ol style="list-style-type: decimal">
<li>By adjusting the number of bins via the <code>bins</code> argument to <code>geom_histogram()</code>.</li>
<li>By adjusting the width of the bins via the <code>binwidth</code> argument to <code>geom_histogram()</code>.</li>
</ol>
<p>Using the first method, we have the power to specify how many bins we would like to cut the x-axis up in. As mentioned in the previous section, the default number of bins is 30. We can override this default, to say 40 bins, as follows:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="data-visualization.html#cb13-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> weather, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> temp)) <span class="sc">+</span></span>
<span id="cb13-2"><a href="data-visualization.html#cb13-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">40</span>, <span class="at">color =</span> <span class="st">&quot;white&quot;</span>)</span></code></pre></div>
<p>Using the second method, instead of specifying the number of bins, we specify the width of the bins by using the <code>binwidth</code> argument in the <code>geom_histogram()</code> layer. For example, let’s set the width of each bin to be 10°F.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="data-visualization.html#cb14-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> weather, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> temp)) <span class="sc">+</span></span>
<span id="cb14-2"><a href="data-visualization.html#cb14-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">10</span>, <span class="at">color =</span> <span class="st">&quot;white&quot;</span>)</span></code></pre></div>
<p>We compare both resulting histograms side-by-side in Figure <a href="data-visualization.html#fig:hist-bins">22.12</a>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:hist-bins"></span>
<img src="_main_files/figure-html/hist-bins-1.png" alt="Setting histogram bins in two ways." width="\textwidth" />
<p class="caption">
Figure 22.12: Setting histogram bins in two ways.
</p>
</div>
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC2.14)</strong> What does changing the number of bins from 30 to 40 tell us about the distribution of temperatures?</p>
<p><strong>(LC2.15)</strong> Would you classify the distribution of temperatures as symmetric or skewed in one direction or another?</p>
<p><strong>(LC2.16)</strong> What would you guess is the “center” value in this distribution? Why did you make that choice?</p>
<p><strong>(LC2.17)</strong> Is this data spread out greatly from the center or is it close? Why?</p>
<div class="learncheck">

</div>
</div>
<div id="summary-2" class="section level3 hasAnchor" number="22.5.3">
<h3><span class="header-section-number">22.5.3</span> Summary<a href="data-visualization.html#summary-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Histograms, unlike scatterplots and linegraphs, present information on only a single numerical variable. Specifically, they are visualizations of the distribution of the numerical variable in question.</p>
</div>
</div>
<div id="facets" class="section level2 hasAnchor" number="22.6">
<h2><span class="header-section-number">22.6</span> Facets<a href="data-visualization.html#facets" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Before continuing with the next of the 5NG, let’s briefly introduce a new concept called <em>faceting</em>. Faceting is used when we’d like to split a particular visualization by the values of another variable. This will create multiple copies of the same type of plot with matching x and y axes, but whose content will differ.</p>
<p>For example, suppose we were interested in looking at how the histogram of hourly temperature recordings at the three NYC airports we saw in Figure <a href="data-visualization.html#fig:histogramexample">22.9</a> differed in each month. We could “split” this histogram by the 12 possible months in a given year. In other words, we would plot histograms of <code>temp</code> for each <code>month</code> separately. We do this by adding <code>facet_wrap(~ month)</code> layer. Note the <code>~</code> is a “tilde” and can generally be found on the key next to the “1” key on US keyboards. The tilde is required and you’ll receive the error <code>Error in as.quoted(facets) : object 'month' not found</code> if you don’t include it here.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="data-visualization.html#cb15-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> weather, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> temp)) <span class="sc">+</span></span>
<span id="cb15-2"><a href="data-visualization.html#cb15-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">color =</span> <span class="st">&quot;white&quot;</span>) <span class="sc">+</span></span>
<span id="cb15-3"><a href="data-visualization.html#cb15-3" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> month)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:facethistogram"></span>
<img src="_main_files/figure-html/facethistogram-1.png" alt="Faceted histogram of hourly temperatures by month." width="\textwidth" />
<p class="caption">
Figure 22.13: Faceted histogram of hourly temperatures by month.
</p>
</div>
<p>We can also specify the number of rows and columns in the grid by using the <code>nrow</code> and <code>ncol</code> arguments inside of <code>facet_wrap()</code>. For example, say we would like our faceted histogram to have 4 rows instead of 3. We simply add an <code>nrow = 4</code> argument to <code>facet_wrap(~ month)</code>.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="data-visualization.html#cb16-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> weather, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> temp)) <span class="sc">+</span></span>
<span id="cb16-2"><a href="data-visualization.html#cb16-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>, <span class="at">color =</span> <span class="st">&quot;white&quot;</span>) <span class="sc">+</span></span>
<span id="cb16-3"><a href="data-visualization.html#cb16-3" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> month, <span class="at">nrow =</span> <span class="dv">4</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:facethistogram2"></span>
<img src="_main_files/figure-html/facethistogram2-1.png" alt="Faceted histogram with 4 instead of 3 rows." width="\textwidth" />
<p class="caption">
Figure 22.14: Faceted histogram with 4 instead of 3 rows.
</p>
</div>
<p>Observe in both Figures <a href="data-visualization.html#fig:facethistogram">22.13</a> and <a href="data-visualization.html#fig:facethistogram2">22.14</a> that as we might expect in the Northern Hemisphere, temperatures tend to be higher in the summer months, while they tend to be lower in the winter.</p>
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC2.18)</strong> What other things do you notice about this faceted plot? How does a faceted plot help us see relationships between two variables?</p>
<p><strong>(LC2.19)</strong> What do the numbers 1-12 correspond to in the plot? What about 25, 50, 75, 100?</p>
<p><strong>(LC2.20)</strong> For which types of datasets would faceted plots not work well in comparing relationships between variables? Give an example describing the nature of these variables and other important characteristics.</p>
<p><strong>(LC2.21)</strong> Does the <code>temp</code> variable in the <code>weather</code> dataset have a lot of variability? Why do you say that?</p>
<div class="learncheck">

</div>
</div>
<div id="boxplots" class="section level2 hasAnchor" number="22.7">
<h2><span class="header-section-number">22.7</span> 5NG#4: Boxplots<a href="data-visualization.html#boxplots" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>While faceted histograms are one type of visualization used to compare the distribution of a numerical variable split by the values of another variable, another type of visualization that achieves this same goal is a <em>side-by-side boxplot</em>. A boxplot is constructed from the information provided in the <em>five-number summary</em> of a numerical variable (see Appendix <a href="#appendix-stat-terms"><strong>??</strong></a>).</p>
<p>To keep things simple for now, let’s only consider the 2141 hourly temperature recordings for the month of November, each represented as a jittered point in Figure <a href="data-visualization.html#fig:nov1">22.15</a>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:nov1"></span>
<img src="_main_files/figure-html/nov1-1.png" alt="November temperatures represented as jittered points." width="\textwidth" />
<p class="caption">
Figure 22.15: November temperatures represented as jittered points.
</p>
</div>
<p>These 2141 observations have the following <em>five-number summary</em>:</p>
<ol style="list-style-type: decimal">
<li>Minimum: 21°F</li>
<li>First quartile (25th percentile): 36°F</li>
<li>Median (second quartile, 50th percentile): 45°F</li>
<li>Third quartile (75th percentile): 52°F</li>
<li>Maximum: 71°F</li>
</ol>
<p>In the leftmost plot of Figure <a href="data-visualization.html#fig:nov2">22.16</a>, let’s mark these 5 values with dashed horizontal lines on top of the 2141 points. In the middle plot of Figure <a href="data-visualization.html#fig:nov2">22.16</a> let’s add the <em>boxplot</em>. In the rightmost plot of Figure <a href="data-visualization.html#fig:nov2">22.16</a>, let’s remove the points and the dashed horizontal lines for clarity’s sake.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:nov2"></span>
<img src="_main_files/figure-html/nov2-1.png" alt="Building up a boxplot of November temperatures." width="\textwidth" />
<p class="caption">
Figure 22.16: Building up a boxplot of November temperatures.
</p>
</div>
<p>What the boxplot does is visually summarize the 2141 points by cutting the 2141 temperature recordings into <em>quartiles</em> at the dashed lines, where each quartile contains roughly 2141 <span class="math inline">\(\div\)</span> 4 <span class="math inline">\(\approx\)</span> 535 observations. Thus</p>
<ol style="list-style-type: decimal">
<li>25% of points fall below the bottom edge of the box, which is the first quartile of 36°F. In other words, 25% of observations were below 36°F.</li>
<li>25% of points fall between the bottom edge of the box and the solid middle line, which is the median of 45°F. Thus, 25% of observations were between 36°F and 45°F and 50% of observations were below 45°F.</li>
<li>25% of points fall between the solid middle line and the top edge of the box, which is the third quartile of 52°F. It follows that 25% of observations were between 45°F and 52°F and 75% of observations were below 52°F.</li>
<li>25% of points fall above the top edge of the box. In other words, 25% of observations were above 52°F.</li>
<li>The middle 50% of points lie within the <em>interquartile range (IQR)</em> between the first and third quartile. Thus, the IQR for this example is 52 - 36 = 16°F. The interquartile range is a measure of a numerical variable’s <em>spread</em>.</li>
</ol>
<p>Furthermore, in the rightmost plot of Figure <a href="data-visualization.html#fig:nov2">22.16</a>, we see the <em>whiskers</em> of the boxplot. The whiskers stick out from either end of the box all the way to the minimum and maximum observed temperatures of 21°F and 71°F, respectively. However, the whiskers don’t always extend to the smallest and largest observed values as they do here. They in fact extend no more than 1.5 <span class="math inline">\(\times\)</span> the interquartile range from either end of the box. In this case of the November temperatures, no more than 1.5 <span class="math inline">\(\times\)</span> 16°F = 24°F from either end of the box. Any observed values outside this range get marked with points called <em>outliers</em>, which we’ll see in the next section.</p>
<div id="geomboxplot" class="section level3 hasAnchor" number="22.7.1">
<h3><span class="header-section-number">22.7.1</span> Boxplots via <code>geom_boxplot</code><a href="data-visualization.html#geomboxplot" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s now create a side-by-side boxplot of hourly temperatures split by the 12 months as we did previously with the faceted histograms. We do this by mapping the <code>month</code> variable to the x-position aesthetic, the <code>temp</code> variable to the y-position aesthetic, and by adding a <code>geom_boxplot()</code> layer:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="data-visualization.html#cb17-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> weather, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> month, <span class="at">y =</span> temp)) <span class="sc">+</span></span>
<span id="cb17-2"><a href="data-visualization.html#cb17-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:badbox"></span>
<img src="_main_files/figure-html/badbox-1.png" alt="Invalid boxplot specification." width="\textwidth" />
<p class="caption">
Figure 22.17: Invalid boxplot specification.
</p>
</div>
<pre><code>Warning messages:
1: Continuous x aesthetic -- did you forget aes(group=...)? 
2: Removed 1 rows containing non-finite values (stat_boxplot). </code></pre>
<p>Observe in Figure <a href="data-visualization.html#fig:badbox">22.17</a> that this plot does not provide information about temperature separated by month. The first warning message clues us in as to why. It is telling us that we have a “continuous”, or numerical variable, on the x-position aesthetic. Boxplots, however, require a categorical variable to be mapped to the x-position aesthetic. The second warning message is identical to the warning message when plotting a histogram of hourly temperatures: that one of the values was recorded as <code>NA</code> missing.</p>
<p>We can convert the numerical variable <code>month</code> into a <code>factor</code> categorical variable by using the <code>factor()</code> function. So after applying <code>factor(month)</code>, month goes from having numerical values just the 1, 2, …, and 12 to having an associated ordering. With this ordering, <code>ggplot()</code> now knows how to work with this variable to produce the needed plot.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="data-visualization.html#cb19-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> weather, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(month), <span class="at">y =</span> temp)) <span class="sc">+</span></span>
<span id="cb19-2"><a href="data-visualization.html#cb19-2" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:monthtempbox"></span>
<img src="_main_files/figure-html/monthtempbox-1.png" alt="Side-by-side boxplot of temperature split by month." width="\textwidth" />
<p class="caption">
Figure 22.18: Side-by-side boxplot of temperature split by month.
</p>
</div>
<p>The resulting Figure <a href="data-visualization.html#fig:monthtempbox">22.18</a> shows 12 separate “box and whiskers” plots similar to the rightmost plot of Figure <a href="data-visualization.html#fig:nov2">22.16</a> of only November temperatures. Thus the different boxplots are shown “side-by-side.”</p>
<ul>
<li>The “box” portions of the visualization represent the 1st quartile, the median (the 2nd quartile), and the 3rd quartile.</li>
<li>The height of each box (the value of the 3rd quartile minus the value of the 1st quartile) is the interquartile range (IQR). It is a measure of the spread of the middle 50% of values, with longer boxes indicating more variability.</li>
<li>The “whisker” portions of these plots extend out from the bottoms and tops of the boxes and represent points less than the 25th percentile and greater than the 75th percentiles, respectively. They’re set to extend out no more than <span class="math inline">\(1.5 \times IQR\)</span> units away from either end of the boxes. We say “no more than” because the ends of the whiskers have to correspond to observed temperatures. The length of these whiskers show how the data outside the middle 50% of values vary, with longer whiskers indicating more variability.</li>
<li>The dots representing values falling outside the whiskers are called <em>outliers</em>. These can be thought of as anomalous (“out-of-the-ordinary”) values.</li>
</ul>
<p>It is important to keep in mind that the definition of an outlier is somewhat arbitrary and not absolute. In this case, they are defined by the length of the whiskers, which are no more than <span class="math inline">\(1.5 \times IQR\)</span> units long for each boxplot. Looking at this side-by-side plot we can see, as expected, that summer months (6 through 8) have higher median temperatures as evidenced by the higher solid lines in the middle of the boxes. We can easily compare temperatures across months by drawing imaginary horizontal lines across the plot. Furthermore, the heights of the 12 boxes as quantified by the interquartile ranges are informative too; they tell us about variability, or spread, of temperatures recorded in a given month.</p>
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC2.22)</strong> What does the dot at the bottom of the plot for May correspond to? Explain what might have occurred in May to produce this point.</p>
<p><strong>(LC2.23)</strong> Which months have the highest variability in temperature? What reasons can you give for this?</p>
<p><strong>(LC2.24)</strong> We looked at the distribution of the numerical variable <code>temp</code> split by the numerical variable <code>month</code> that we converted using the <code>factor()</code> function in order to make a side-by-side boxplot. Why would a boxplot of <code>temp</code> split by the numerical variable <code>pressure</code> similarly converted to a categorical variable using the <code>factor()</code> not be informative?</p>
<p><strong>(LC2.25)</strong> Boxplots provide a simple way to identify outliers. Why may outliers be easier to identify when looking at a boxplot instead of a faceted histogram?</p>
<div class="learncheck">

</div>
</div>
<div id="summary-3" class="section level3 hasAnchor" number="22.7.2">
<h3><span class="header-section-number">22.7.2</span> Summary<a href="data-visualization.html#summary-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Side-by-side boxplots provide us with a way to compare the distribution of a numerical variable across multiple values of another variable. One can see where the median falls across the different groups by comparing the solid lines in the center of the boxes.</p>
<p>To study the spread of a numerical variable within one of the boxes, look at both the length of the box and also how far the whiskers extend from either end of the box. Outliers are even more easily identified when looking at a boxplot than when looking at a histogram as they are marked with distinct points.</p>
</div>
</div>
<div id="geombar" class="section level2 hasAnchor" number="22.8">
<h2><span class="header-section-number">22.8</span> 5NG#5: Barplots<a href="data-visualization.html#geombar" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Both histograms and boxplots are tools to visualize the distribution of numerical variables. Another commonly desired task is to visualize the distribution of a categorical variable. This is a simpler task, as we are simply counting different categories within a categorical variable, also known as the <em>levels</em> of the categorical variable. Often the best way to visualize these different counts, also known as <em>frequencies</em>, is with barplots (also called barcharts).</p>
<p>One complication, however, is how your data is represented. Is the categorical variable of interest “pre-counted” or not? For example, run the following code that manually creates two data frames representing a collection of fruit: 3 apples and 2 oranges.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="data-visualization.html#cb20-1" tabindex="-1"></a>fruits <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb20-2"><a href="data-visualization.html#cb20-2" tabindex="-1"></a>  <span class="at">fruit =</span> <span class="fu">c</span>(<span class="st">&quot;apple&quot;</span>, <span class="st">&quot;apple&quot;</span>, <span class="st">&quot;orange&quot;</span>, <span class="st">&quot;apple&quot;</span>, <span class="st">&quot;orange&quot;</span>)</span>
<span id="cb20-3"><a href="data-visualization.html#cb20-3" tabindex="-1"></a>)</span>
<span id="cb20-4"><a href="data-visualization.html#cb20-4" tabindex="-1"></a>fruits_counted <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb20-5"><a href="data-visualization.html#cb20-5" tabindex="-1"></a>  <span class="at">fruit =</span> <span class="fu">c</span>(<span class="st">&quot;apple&quot;</span>, <span class="st">&quot;orange&quot;</span>),</span>
<span id="cb20-6"><a href="data-visualization.html#cb20-6" tabindex="-1"></a>  <span class="at">number =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">2</span>)</span>
<span id="cb20-7"><a href="data-visualization.html#cb20-7" tabindex="-1"></a>)</span></code></pre></div>
<p>We see both the <code>fruits</code> and <code>fruits_counted</code> data frames represent the same collection of fruit. Whereas <code>fruits</code> just lists the fruit individually…</p>
<pre><code>## # A tibble: 5 × 1
##   fruit 
##   &lt;chr&gt; 
## 1 apple 
## 2 apple 
## 3 orange
## 4 apple 
## 5 orange</code></pre>
<p>… <code>fruits_counted</code> has a variable <code>count</code> which represent the “pre-counted” values of each fruit.</p>
<pre><code>## # A tibble: 2 × 2
##   fruit  number
##   &lt;chr&gt;   &lt;dbl&gt;
## 1 apple       3
## 2 orange      2</code></pre>
<p>Depending on how your categorical data is represented, you’ll need to add a different <code>geom</code>etric layer type to your <code>ggplot()</code> to create a barplot, as we now explore.</p>
<div id="barplots-via-geom_bar-or-geom_col" class="section level3 hasAnchor" number="22.8.1">
<h3><span class="header-section-number">22.8.1</span> Barplots via <code>geom_bar</code> or <code>geom_col</code><a href="data-visualization.html#barplots-via-geom_bar-or-geom_col" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s generate barplots using these two different representations of the same basket of fruit: 3 apples and 2 oranges. Using the <code>fruits</code> data frame where all 5 fruits are listed individually in 5 rows, we map the <code>fruit</code> variable to the x-position aesthetic and add a <code>geom_bar()</code> layer:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="data-visualization.html#cb23-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> fruits, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> fruit)) <span class="sc">+</span></span>
<span id="cb23-2"><a href="data-visualization.html#cb23-2" tabindex="-1"></a>  <span class="fu">geom_bar</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:geombar"></span>
<img src="_main_files/figure-html/geombar-1.png" alt="Barplot when counts are not pre-counted." width="\textwidth" />
<p class="caption">
Figure 22.19: Barplot when counts are not pre-counted.
</p>
</div>
<p>However, using the <code>fruits_counted</code> data frame where the fruits have been “pre-counted”, we once again map the <code>fruit</code> variable to the x-position aesthetic, but here we also map the <code>count</code> variable to the y-position aesthetic, and add a <code>geom_col()</code> layer instead.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="data-visualization.html#cb24-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> fruits_counted, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> fruit, <span class="at">y =</span> number)) <span class="sc">+</span></span>
<span id="cb24-2"><a href="data-visualization.html#cb24-2" tabindex="-1"></a>  <span class="fu">geom_col</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:geomcol"></span>
<img src="_main_files/figure-html/geomcol-1.png" alt="Barplot when counts are pre-counted." width="\textwidth" />
<p class="caption">
Figure 22.20: Barplot when counts are pre-counted.
</p>
</div>
<p>Compare the barplots in Figures <a href="data-visualization.html#fig:geombar">22.19</a> and <a href="data-visualization.html#fig:geomcol">22.20</a>. They are identical because they reflect counts of the same five fruits. However, depending on how our categorical data is represented, either “pre-counted” or not, we must add a different <code>geom</code> layer. When the categorical variable whose distribution you want to visualize</p>
<ul>
<li>Is <em>not</em> pre-counted in your data frame, we use <code>geom_bar()</code>.</li>
<li>Is pre-counted in your data frame, we use <code>geom_col()</code> with the y-position aesthetic mapped to the variable that has the counts.</li>
</ul>
<p>Let’s now go back to the <code>flights</code> data frame in the <code>nycflights13</code> package and visualize the distribution of the categorical variable <code>carrier</code>. In other words, let’s visualize the number of domestic flights out of New York City each airline company flew in 2013. Recall from Subsection <a href="getting-started.html#exploredataframes">6.5.3</a> when you first explored the <code>flights</code> data frame, you saw that each row corresponds to a flight. In other words, the <code>flights</code> data frame is more like the <code>fruits</code> data frame than the <code>fruits_counted</code> data frame because the flights have not been pre-counted by <code>carrier</code>. Thus we should use <code>geom_bar()</code> instead of <code>geom_col()</code> to create a barplot. Much like a <code>geom_histogram()</code>, there is only one variable in the <code>aes()</code> aesthetic mapping: the variable <code>carrier</code> gets mapped to the <code>x</code>-position. As a difference though, histograms have bars that touch whereas bar graphs have white space between the bars going from left to right.</p>

<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="data-visualization.html#cb25-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> flights, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> carrier)) <span class="sc">+</span></span>
<span id="cb25-2"><a href="data-visualization.html#cb25-2" tabindex="-1"></a>  <span class="fu">geom_bar</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:flightsbar"></span>
<img src="_main_files/figure-html/flightsbar-1.png" alt="Number of flights departing NYC in 2013 by airline using geom_bar()." width="\textwidth" />
<p class="caption">
Figure 22.21: Number of flights departing NYC in 2013 by airline using geom_bar().
</p>
</div>
<p>Observe in Figure <a href="data-visualization.html#fig:flightsbar">22.21</a> that United Airlines (UA), JetBlue Airways (B6), and ExpressJet Airlines (EV) had the most flights depart NYC in 2013. If you don’t know which airlines correspond to which carrier codes, then run <code>View(airlines)</code> to see a directory of airlines. For example, B6 is JetBlue Airways. Alternatively, say you had a data frame where the number of flights for each <code>carrier</code> was pre-counted as in Table <a href="data-visualization.html#tab:flights-counted">22.3</a>.</p>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:flights-counted">Table 22.3: </span>Number of flights pre-counted for each carrier
</caption>
<thead>
<tr>
<th style="text-align:left;">
carrier
</th>
<th style="text-align:right;">
number
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
9E
</td>
<td style="text-align:right;">
18460
</td>
</tr>
<tr>
<td style="text-align:left;">
AA
</td>
<td style="text-align:right;">
32729
</td>
</tr>
<tr>
<td style="text-align:left;">
AS
</td>
<td style="text-align:right;">
714
</td>
</tr>
<tr>
<td style="text-align:left;">
B6
</td>
<td style="text-align:right;">
54635
</td>
</tr>
<tr>
<td style="text-align:left;">
DL
</td>
<td style="text-align:right;">
48110
</td>
</tr>
<tr>
<td style="text-align:left;">
EV
</td>
<td style="text-align:right;">
54173
</td>
</tr>
<tr>
<td style="text-align:left;">
F9
</td>
<td style="text-align:right;">
685
</td>
</tr>
<tr>
<td style="text-align:left;">
FL
</td>
<td style="text-align:right;">
3260
</td>
</tr>
<tr>
<td style="text-align:left;">
HA
</td>
<td style="text-align:right;">
342
</td>
</tr>
<tr>
<td style="text-align:left;">
MQ
</td>
<td style="text-align:right;">
26397
</td>
</tr>
<tr>
<td style="text-align:left;">
OO
</td>
<td style="text-align:right;">
32
</td>
</tr>
<tr>
<td style="text-align:left;">
UA
</td>
<td style="text-align:right;">
58665
</td>
</tr>
<tr>
<td style="text-align:left;">
US
</td>
<td style="text-align:right;">
20536
</td>
</tr>
<tr>
<td style="text-align:left;">
VX
</td>
<td style="text-align:right;">
5162
</td>
</tr>
<tr>
<td style="text-align:left;">
WN
</td>
<td style="text-align:right;">
12275
</td>
</tr>
<tr>
<td style="text-align:left;">
YV
</td>
<td style="text-align:right;">
601
</td>
</tr>
</tbody>
</table>
<p>In order to create a barplot visualizing the distribution of the categorical variable <code>carrier</code> in this case, we would now use <code>geom_col()</code> instead of <code>geom_bar()</code>, with an additional <code>y = number</code> in the aesthetic mapping on top of the <code>x = carrier</code>. The resulting barplot would be identical to Figure <a href="data-visualization.html#fig:flightsbar">22.21</a>.</p>
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC2.26)</strong> Why are histograms inappropriate for categorical variables?</p>
<p><strong>(LC2.27)</strong> What is the difference between histograms and barplots?</p>
<p><strong>(LC2.28)</strong> How many Envoy Air flights departed NYC in 2013?</p>
<p><strong>(LC2.29)</strong> What was the 7th highest airline for departed flights from NYC in 2013? How could we better present the table to get this answer quickly?</p>
<div class="learncheck">

</div>
</div>
<div id="must-avoid-pie-charts" class="section level3 hasAnchor" number="22.8.2">
<h3><span class="header-section-number">22.8.2</span> Must avoid pie charts!<a href="data-visualization.html#must-avoid-pie-charts" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>One of the most common plots used to visualize the distribution of categorical data is the pie chart. While they may seem harmless enough, pie charts actually present a problem in that humans are unable to judge angles well. As Naomi Robbins describes in her book, <em>Creating More Effective Graphs</em> <span class="citation">[@robbins2013]</span>, we overestimate angles greater than 90 degrees and we underestimate angles less than 90 degrees. In other words, it is difficult for us to determine the relative size of one piece of the pie compared to another.</p>
<p>Let’s examine the same data used in our previous barplot of the number of flights departing NYC by airline in Figure <a href="data-visualization.html#fig:flightsbar">22.21</a>, but this time we will use a pie chart in Figure <a href="data-visualization.html#fig:carrierpie">22.22</a>. Try to answer the following questions:</p>
<ul>
<li>How much larger is the portion of the pie for ExpressJet Airlines (<code>EV</code>) compared to US Airways (<code>US</code>)?</li>
<li>What is the third largest carrier in terms of departing flights?</li>
<li>How many carriers have fewer flights than United Airlines (<code>UA</code>)?</li>
</ul>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:carrierpie"></span>
<img src="_main_files/figure-html/carrierpie-1.png" alt="The dreaded pie chart." width="\textwidth" />
<p class="caption">
Figure 22.22: The dreaded pie chart.
</p>
</div>
<p>While it is quite difficult to answer these questions when looking at the pie chart in Figure <a href="data-visualization.html#fig:carrierpie">22.22</a>, we can much more easily answer these questions using the barchart in Figure <a href="data-visualization.html#fig:flightsbar">22.21</a>. This is true since barplots present the information in a way such that comparisons between categories can be made with single horizontal lines, whereas pie charts present the information in a way such that comparisons must be made by comparing angles.</p>
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC2.30)</strong> Why should pie charts be avoided and replaced by barplots?</p>
<p><strong>(LC2.31)</strong> Why do you think people continue to use pie charts?</p>
<div class="learncheck">

</div>
</div>
<div id="two-categ-barplot" class="section level3 hasAnchor" number="22.8.3">
<h3><span class="header-section-number">22.8.3</span> Two categorical variables<a href="data-visualization.html#two-categ-barplot" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Barplots are a very common way to visualize the frequency of different categories, or levels, of a single categorical variable. Another use of barplots is to visualize the <em>joint</em> distribution of two categorical variables at the same time. Let’s examine the <em>joint</em> distribution of outgoing domestic flights from NYC by <code>carrier</code> as well as <code>origin</code>. In other words, the number of flights for each <code>carrier</code> and <code>origin</code> combination.</p>
<p>For example, the number of WestJet flights from <code>JFK</code>, the number of WestJet flights from <code>LGA</code>, the number of WestJet flights from <code>EWR</code>, the number of American Airlines flights from <code>JFK</code>, and so on. Recall the <code>ggplot()</code> code that created the barplot of <code>carrier</code> frequency in Figure <a href="data-visualization.html#fig:flightsbar">22.21</a>:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="data-visualization.html#cb26-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> flights, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> carrier)) <span class="sc">+</span> </span>
<span id="cb26-2"><a href="data-visualization.html#cb26-2" tabindex="-1"></a>  <span class="fu">geom_bar</span>()</span></code></pre></div>
<p>We can now map the additional variable <code>origin</code> by adding a <code>fill = origin</code> inside the <code>aes()</code> aesthetic mapping.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="data-visualization.html#cb27-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> flights, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> carrier, <span class="at">fill =</span> origin)) <span class="sc">+</span></span>
<span id="cb27-2"><a href="data-visualization.html#cb27-2" tabindex="-1"></a>  <span class="fu">geom_bar</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:flights-stacked-bar"></span>
<img src="_main_files/figure-html/flights-stacked-bar-1.png" alt="Stacked barplot of flight amount by carrier and origin." width="\textwidth" />
<p class="caption">
Figure 22.23: Stacked barplot of flight amount by carrier and origin.
</p>
</div>
<p>Figure <a href="data-visualization.html#fig:flights-stacked-bar">22.23</a> is an example of a <em>stacked barplot</em>. While simple to make, in certain aspects it is not ideal. For example, it is difficult to compare the heights of the different colors between the bars, corresponding to comparing the number of flights from each <code>origin</code> airport between the carriers.</p>
<p>Before we continue, let’s address some common points of confusion among new R users. First, the <code>fill</code> aesthetic corresponds to the color used to fill the bars, while the <code>color</code> aesthetic corresponds to the color of the outline of the bars. This is identical to how we added color to our histogram in Subsection <a href="data-visualization.html#geomhistogram">22.5.1</a>: we set the outline of the bars to white by setting <code>color = "white"</code> and the colors of the bars to blue steel by setting <code>fill = "steelblue"</code>. Observe in Figure <a href="data-visualization.html#fig:flights-stacked-bar-color">22.24</a> that mapping <code>origin</code> to <code>color</code> and not <code>fill</code> yields grey bars with different colored outlines.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="data-visualization.html#cb28-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> flights, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> carrier, <span class="at">color =</span> origin)) <span class="sc">+</span></span>
<span id="cb28-2"><a href="data-visualization.html#cb28-2" tabindex="-1"></a>  <span class="fu">geom_bar</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:flights-stacked-bar-color"></span>
<img src="_main_files/figure-html/flights-stacked-bar-color-1.png" alt="Stacked barplot with color aesthetic used instead of fill." width="\textwidth" />
<p class="caption">
Figure 22.24: Stacked barplot with color aesthetic used instead of fill.
</p>
</div>
<p>Second, note that <code>fill</code> is another aesthetic mapping much like <code>x</code>-position; thus we were careful to include it within the parentheses of the <code>aes()</code> mapping. The following code, where the <code>fill</code> aesthetic is specified outside the <code>aes()</code> mapping will yield an error. This is a fairly common error that new <code>ggplot</code> users make:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="data-visualization.html#cb29-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> flights, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> carrier), <span class="at">fill =</span> origin) <span class="sc">+</span></span>
<span id="cb29-2"><a href="data-visualization.html#cb29-2" tabindex="-1"></a>  <span class="fu">geom_bar</span>()</span></code></pre></div>
<p>An alternative to stacked barplots are <em>side-by-side barplots</em>, also known as <em>dodged barplots</em>, as seen in Figure <a href="data-visualization.html#fig:flights-dodged-bar-color">22.25</a>. The code to create a side-by-side barplot is identical to the code to create a stacked barplot, but with a <code>position = "dodge"</code> argument added to <code>geom_bar()</code>. In other words, we are overriding the default barplot type, which is a <em>stacked</em> barplot, and specifying it to be a side-by-side barplot instead.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="data-visualization.html#cb30-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> flights, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> carrier, <span class="at">fill =</span> origin)) <span class="sc">+</span></span>
<span id="cb30-2"><a href="data-visualization.html#cb30-2" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">&quot;dodge&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:flights-dodged-bar-color"></span>
<img src="_main_files/figure-html/flights-dodged-bar-color-1.png" alt="Side-by-side barplot comparing number of flights by carrier and origin." width="\textwidth" />
<p class="caption">
Figure 22.25: Side-by-side barplot comparing number of flights by carrier and origin.
</p>
</div>
<p>Note the width of the bars for <code>AS</code>, <code>F9</code>, <code>FL</code>, <code>HA</code> and <code>YV</code> is different than the others. We can make one tweak to the <code>position</code> argument to get them to be the same size in terms of width as the other bars by using the more robust <code>position_dodge()</code> function.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="data-visualization.html#cb31-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> flights, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> carrier, <span class="at">fill =</span> origin)) <span class="sc">+</span></span>
<span id="cb31-2"><a href="data-visualization.html#cb31-2" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">preserve =</span> <span class="st">&quot;single&quot;</span>))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:flights-dodged-bar-color-tweak"></span>
<img src="_main_files/figure-html/flights-dodged-bar-color-tweak-1.png" alt="Side-by-side barplot comparing number of flights by carrier and origin (with formatting tweak)." width="\textwidth" />
<p class="caption">
Figure 22.26: Side-by-side barplot comparing number of flights by carrier and origin (with formatting tweak).
</p>
</div>
<p>Lastly, another type of barplot is a <em>faceted barplot</em>. Recall in Section <a href="data-visualization.html#facets">22.6</a> we visualized the distribution of hourly temperatures at the 3 NYC airports <em>split</em> by month using facets. We apply the same principle to our barplot visualizing the frequency of <code>carrier</code> split by <code>origin</code>: instead of mapping <code>origin</code> to <code>fill</code> we include it as the variable to create small multiples of the plot across the levels of <code>origin</code>.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="data-visualization.html#cb32-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> flights, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> carrier)) <span class="sc">+</span></span>
<span id="cb32-2"><a href="data-visualization.html#cb32-2" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb32-3"><a href="data-visualization.html#cb32-3" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> origin, <span class="at">ncol =</span> <span class="dv">1</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:facet-bar-vert"></span>
<img src="_main_files/figure-html/facet-bar-vert-1.png" alt="Faceted barplot comparing the number of flights by carrier and origin." width="\textwidth" />
<p class="caption">
Figure 22.27: Faceted barplot comparing the number of flights by carrier and origin.
</p>
</div>
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC2.32)</strong> What kinds of questions are not easily answered by looking at Figure <a href="data-visualization.html#fig:flights-stacked-bar">22.23</a>?</p>
<p><strong>(LC2.33)</strong> What can you say, if anything, about the relationship between airline and airport in NYC in 2013 in regards to the number of departing flights?</p>
<p><strong>(LC2.34)</strong> Why might the side-by-side barplot be preferable to a stacked barplot in this case?</p>
<p><strong>(LC2.35)</strong> What are the disadvantages of using a dodged barplot, in general?</p>
<p><strong>(LC2.36)</strong> Why is the faceted barplot preferred to the side-by-side and stacked barplots in this case?</p>
<p><strong>(LC2.37)</strong> What information about the different carriers at different airports is more easily seen in the faceted barplot?</p>
<div class="learncheck">

</div>
</div>
<div id="summary-4" class="section level3 hasAnchor" number="22.8.4">
<h3><span class="header-section-number">22.8.4</span> Summary<a href="data-visualization.html#summary-4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Barplots are a common way of displaying the distribution of a categorical variable, or in other words the frequency with which the different categories (also called <em>levels</em>) occur. They are easy to understand and make it easy to make comparisons across levels. Furthermore, when trying to visualize the relationship of two categorical variables, you have many options: stacked barplots, side-by-side barplots, and faceted barplots. Depending on what aspect of the relationship you are trying to emphasize, you will need to make a choice between these three types of barplots and own that choice.</p>
</div>
</div>
<div id="data-vis-conclusion" class="section level2 hasAnchor" number="22.9">
<h2><span class="header-section-number">22.9</span> Conclusion<a href="data-visualization.html#data-vis-conclusion" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="summary-table" class="section level3 hasAnchor" number="22.9.1">
<h3><span class="header-section-number">22.9.1</span> Summary table<a href="data-visualization.html#summary-table" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s recap all five of the five named graphs (5NG) in Table <a href="data-visualization.html#tab:viz-summary-table">22.4</a> summarizing their differences. Using these 5NG, you’ll be able to visualize the distributions and relationships of variables contained in a wide array of datasets. This will be even more the case as we start to map more variables to more of each <code>geom</code>etric object’s <code>aes</code>thetic attribute options, further unlocking the awesome power of the <code>ggplot2</code> package.</p>
<table>
<caption>
<span id="tab:viz-summary-table">Table 22.4: </span>Summary of Five Named Graphs
</caption>
<thead>
<tr>
<th style="text-align:right;">
</th>
<th style="text-align:left;">
Named graph
</th>
<th style="text-align:left;">
Shows
</th>
<th style="text-align:left;">
Geometric object
</th>
<th style="text-align:left;">
Notes
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
Scatterplot
</td>
<td style="text-align:left;">
Relationship between 2 numerical variables
</td>
<td style="text-align:left;">
<code>geom_point()</code>
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
Linegraph
</td>
<td style="text-align:left;">
Relationship between 2 numerical variables
</td>
<td style="text-align:left;">
<code>geom_line()</code>
</td>
<td style="text-align:left;">
Used when there is a sequential order to x-variable, e.g., time
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
Histogram
</td>
<td style="text-align:left;">
Distribution of 1 numerical variable
</td>
<td style="text-align:left;">
<code>geom_histogram()</code>
</td>
<td style="text-align:left;">
Facetted histograms show the distribution of 1 numerical variable split by the values of another variable
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:left;">
Boxplot
</td>
<td style="text-align:left;">
Distribution of 1 numerical variable split by the values of another variable
</td>
<td style="text-align:left;">
<code>geom_boxplot()</code>
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:left;">
Barplot
</td>
<td style="text-align:left;">
Distribution of 1 categorical variable
</td>
<td style="text-align:left;">
<code>geom_bar()</code> when counts are not pre-counted, <code>geom_col()</code> when counts are pre-counted
</td>
<td style="text-align:left;">
Stacked, side-by-side, and faceted barplots show the joint distribution of 2 categorical variables
</td>
</tr>
</tbody>
</table>
</div>
<div id="function-argument-specification" class="section level3 hasAnchor" number="22.9.2">
<h3><span class="header-section-number">22.9.2</span> Function argument specification<a href="data-visualization.html#function-argument-specification" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s go over some important points about specifying the arguments (i.e., inputs) to functions. Run the following two segments of code:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="data-visualization.html#cb33-1" tabindex="-1"></a><span class="co"># Segment 1:</span></span>
<span id="cb33-2"><a href="data-visualization.html#cb33-2" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> flights, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> carrier)) <span class="sc">+</span></span>
<span id="cb33-3"><a href="data-visualization.html#cb33-3" tabindex="-1"></a>  <span class="fu">geom_bar</span>()</span>
<span id="cb33-4"><a href="data-visualization.html#cb33-4" tabindex="-1"></a></span>
<span id="cb33-5"><a href="data-visualization.html#cb33-5" tabindex="-1"></a><span class="co"># Segment 2:</span></span>
<span id="cb33-6"><a href="data-visualization.html#cb33-6" tabindex="-1"></a><span class="fu">ggplot</span>(flights, <span class="fu">aes</span>(<span class="at">x =</span> carrier)) <span class="sc">+</span></span>
<span id="cb33-7"><a href="data-visualization.html#cb33-7" tabindex="-1"></a>  <span class="fu">geom_bar</span>()</span></code></pre></div>
<p>You’ll notice that both code segments create the same barplot, even though in the second segment we omitted the <code>data =</code> and <code>mapping =</code> code argument names. This is because the <code>ggplot()</code> function by default assumes that the <code>data</code> argument comes first and the <code>mapping</code> argument comes second. As long as you specify the data frame in question first and the <code>aes()</code> mapping second, you can omit the explicit statement of the argument names <code>data =</code> and <code>mapping =</code>.</p>
<p>Going forward for the rest of this book, all <code>ggplot()</code> code will be like the second segment: with the <code>data =</code> and <code>mapping =</code> explicit naming of the argument omitted with the default ordering of arguments respected. We’ll do this for brevity’s sake; it’s common to see this style when reviewing other R users’ code.</p>
</div>
<div id="additional-resources" class="section level3 hasAnchor" number="22.9.3">
<h3><span class="header-section-number">22.9.3</span> Additional resources<a href="data-visualization.html#additional-resources" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>If you want to further unlock the power of the <code>ggplot2</code> package for data visualization, we suggest that you check out RStudio’s “Data Visualization with ggplot2” cheatsheet. This cheatsheet summarizes much more than what we’ve discussed in this chapter. In particular, it presents many more than the 5 <code>geom</code>etric objects we covered in this chapter while providing quick and easy to read visual descriptions. For all the <code>geom</code>etric objects, it also lists all the possible aesthetic attributes one can tweak. In the current version of RStudio in late 2019, you can access this cheatsheet by going to the RStudio Menu Bar -&gt; Help -&gt; Cheatsheets -&gt; “Data Visualization with ggplot2.” You can see a preview in the figure below. Alternatively, you can preview the cheat sheet by going to the ggplot2 Github page with this <a href="https://github.com/rstudio/cheatsheets/blob/main/data-visualization-2.1.pdf">link</a>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ggplot-cheatsheet"></span>
<img src="images/cheatsheets/ggplot_cheatsheet-1.png" alt="Data Visualization with ggplot2 cheatsheet." width="\textwidth" />
<p class="caption">
Figure 22.28: Data Visualization with ggplot2 cheatsheet.
</p>
</div>
</div>
<div id="whats-to-come-3" class="section level3 hasAnchor" number="22.9.4">
<h3><span class="header-section-number">22.9.4</span> What’s to come<a href="data-visualization.html#whats-to-come-3" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Recall in Figure <a href="data-visualization.html#fig:noalpha">22.2</a> in Section <a href="data-visualization.html#scatterplots">22.3</a> we visualized the relationship between departure delay and arrival delay for Alaska Airlines flights only, rather than <em>all</em> flights. This data is saved in the <code>alaska_flights</code> data frame from the <code>moderndive</code> package.</p>
<p>In reality, the <code>alaska_flights</code> data frame is merely a subset of the <code>flights</code> data frame from the <code>nycflights13</code> package consisting of <em>all</em> flights that left NYC in 2013. We created <code>alaska_flights</code> using the following code that uses the <code>dplyr</code> package for data wrangling:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="data-visualization.html#cb34-1" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb34-2"><a href="data-visualization.html#cb34-2" tabindex="-1"></a></span>
<span id="cb34-3"><a href="data-visualization.html#cb34-3" tabindex="-1"></a>alaska_flights <span class="ot">&lt;-</span> flights <span class="sc">%&gt;%</span> </span>
<span id="cb34-4"><a href="data-visualization.html#cb34-4" tabindex="-1"></a>  <span class="fu">filter</span>(carrier <span class="sc">==</span> <span class="st">&quot;AS&quot;</span>)</span>
<span id="cb34-5"><a href="data-visualization.html#cb34-5" tabindex="-1"></a></span>
<span id="cb34-6"><a href="data-visualization.html#cb34-6" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> alaska_flights, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> dep_delay, <span class="at">y =</span> arr_delay)) <span class="sc">+</span> </span>
<span id="cb34-7"><a href="data-visualization.html#cb34-7" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<p>This code takes the <code>flights</code> data frame and <code>filter()</code> it to only return the 714 rows where <code>carrier</code> is equal to <code>"AS"</code>, Alaska Airlines’ carrier code. (Recall from Section <a href="getting-started.html#code">6.3</a> that testing for equality is specified with <code>==</code> and not <code>=</code>.) The code then cycles back to save the output in a new data frame called <code>alaska_flights</code> using the <code>&lt;-</code> <em>assignment</em> operator.</p>
<p>Similarly, recall in Figure <a href="data-visualization.html#fig:hourlytemp">22.7</a> in Section <a href="data-visualization.html#linegraphs">22.4</a> we visualized hourly temperature recordings at Newark airport only for the first 15 days of January 2013. This data is saved in the <code>early_january_weather</code> data frame from the <code>moderndive</code> package.</p>
<p>In reality, the <code>early_january_weather</code> data frame is merely a subset of the <code>weather</code> data frame from the <code>nycflights13</code> package consisting of <em>all</em> hourly weather observations in 2013 for <em>all</em> three NYC airports. We created <code>early_january_weather</code> using the following <code>dplyr</code> code:</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="data-visualization.html#cb35-1" tabindex="-1"></a>early_january_weather <span class="ot">&lt;-</span> weather <span class="sc">%&gt;%</span> </span>
<span id="cb35-2"><a href="data-visualization.html#cb35-2" tabindex="-1"></a>  <span class="fu">filter</span>(origin <span class="sc">==</span> <span class="st">&quot;EWR&quot;</span> <span class="sc">&amp;</span> month <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> day <span class="sc">&lt;=</span> <span class="dv">15</span>)</span>
<span id="cb35-3"><a href="data-visualization.html#cb35-3" tabindex="-1"></a></span>
<span id="cb35-4"><a href="data-visualization.html#cb35-4" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> early_january_weather, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> time_hour, <span class="at">y =</span> temp)) <span class="sc">+</span></span>
<span id="cb35-5"><a href="data-visualization.html#cb35-5" tabindex="-1"></a>  <span class="fu">geom_line</span>()</span></code></pre></div>
<p>This code pares down the <code>weather</code> data frame to a new data frame <code>early_january_weather</code> consisting of hourly temperature recordings only for <code>origin == "EWR"</code>, <code>month == 1</code>, and day less than or equal to <code>15</code>.</p>
<p>These two code segments are a preview of Chapter <a href="m6a-wrangling-and-tidying-data.html#wrangling">18.2</a> on data wrangling using the <code>dplyr</code> package. Data wrangling is the process of transforming and modifying existing data with the intent of making it more appropriate for analysis purposes. For example, these two code segments used the <code>filter()</code> function to create new data frames (<code>alaska_flights</code> and <code>early_january_weather</code>) by choosing only a subset of rows of existing data frames (<code>flights</code> and <code>weather</code>). In the next chapter, we’ll formally introduce the <code>filter()</code> and other data wrangling functions as well as the <em>pipe operator</em> <code>%&gt;%</code> which allows you to combine multiple data wrangling actions into a single sequential <em>chain</em> of actions. On to Chapter <a href="m6a-wrangling-and-tidying-data.html#wrangling">18.2</a> on data wrangling!</p>

</div>
</div>
</div>
<script src="https://hypothes.is/embed.js" async></script>
            </section>

          </div>
        </div>
      </div>
<a href="viz.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="m7c-practice-visualizing-your-own-data.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
