# M1C: Introduce Yourself to the Class

You will complete the Module 1 Connection activity on Canvas. Please navigate to the corresponding discussion board and respond to the following prompt:

> One of the hardest parts about teaching online classes is getting to know my students! For this week's connection activity, please introduce yourself to me and to your classmates. You might include details like your pronouns, what program you're in, your current (or expected future) job, and what you like to do for fun. I'd also be interested to hear why you're taking this class, what you're hoping to learn, and any big questions or concerns that you have.
> 
> As with all discussion posts in this course, I strongly encourage you to read over and respond to what your classmates have posted. However, as important as meaningful interaction is, I'm skeptical that it can be structured or required, so I will never require you to do so. That said, I do expect that you will make an effort to contribute to meaningful interaction within the class. To help with this, I'm experimenting with the "like" feature in Canvas discussions (and with sorting posts by the number of "likes" they receive, though you won't be able to see others' posts before adding your own). Feel free to use "liking" to add to this interaction!