# M2U: The New(?) and Shiny(?) Science of Data

This chapter draws on material from:

* [Introduction: Why Data Science Needs Feminism](https://data-feminism.mitpress.mit.edu/pub/frfa9szd/release/6) by [Catherine D'Ignazio](http://www.kanarinka.com/) and [Lauren Klein](https://lklein.com/), licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)
* [1: The Power Chapter](https://data-feminism.mitpress.mit.edu/pub/vi8obxh7/release/4) by [Catherine D'Ignazio](http://www.kanarinka.com/) and [Lauren Klein](https://lklein.com/), licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)
* [Version 3: An Introduction to Data Science](https://surface.syr.edu/istpub/165/) by Jeffrey Stanton, licensed under [CC BY-NC-SA 3.0](https://creativecommons.org/licenses/by-nc-sa/3.0/)

Changes to the source material include adding new material; editing, reformatting, and rearranging of original material; adding links; adding or replacing images; changing the citation style; changing original authors' voice to third person; and adding first-person language from current author.

The resulting content is licensed under [CC BY-NC-SA 3.0](https://creativecommons.org/licenses/by-nc-sa/3.0/).

## Data, Data Science, and Big Data

*Data science* refers to an emerging area of work concerned with the collection, preparation, analysis, visualization, management, and preservation of large collections of information, sometimes referred to as *big data*.

### What Are Data?

To introduce *data science*, it makes sense that we ought to talk about *data* first. The word *data* is the plural of the the Latin word *datum*. One quick word before we continue: Because the word *data* is the plural of *datum*, I (and many people) prefer data as a plural noun—hence "What Are Data?" for the section title. (In fact, I think it's funny to define data science as "the science of datums," but that's a terrible joke and I promise I won't do it again in this book). However, it's quite common in American English to treat data as a singular word—so common in fact, that you might notice me trip up and write "What is Data?" at some point. My opinion here is strong enough that I won't mind if you point out when I'm inconsistent but not so strong that I'm going to get picky about how you treat the word—go with whatever comes more naturally to you. 

Even though we rarely use the singular *datum*, it's worth briefly exploring its etymology. The word means "a given"—that is, something taken for granted. That's important: The word *data* was introduced in the mid-seventeenth century to supplement existing terms such as evidence and fact. Identifying information as *data*, rather than as either of those other two terms, served a rhetorical purpose (Poovey, 1998; Posner & Klein, 2017; Rosenberg, 2013). It converted otherwise debatable information into the solid basis for subsequent claims.

Modern usage of the word *data* started in the 1940s and 1950s as practical electronic computers began to input, process, and output data. When computers work with data, all of that data has to be broken down to individual *bits* as the "atoms" that make up data. A bit is a binary unit of data, meaning that it is only capable of representing one of two values: `0` and `1`. That doesn't carry a lot of information by itself (at best, "yes" vs. "no" or `TRUE` vs. `FALSE`). However, by combining bits, we can increase the amount of information that we transmit. For example, even a combination of just two bits can express four different values: `00`, `01`, `10` and `11`. Every time you add a new bit you double the number of possible messages you can send. So three bits would give eight options and four bits would give 16 options.

When we get up to eight bits—which provides 256 different combinations—we finally have something of a reasonably useful size to work with. Eight bits is commonly referred to as a *byte*—this term probably started out as a play on words with the word *bit* (and four bits is sometimes referred to as a *nibble* or a *nybble*, because nerds like jokes). A byte offers enough different combinations to encode all of the letters of the (English) alphabet, including capital and small letters. There is an old rulebook called ASCII—the American Standard Code for Information Interchange—which matches up patterns of eight bits with the letters of the alphabet, punctuation, and a few other odds and ends. For example the bit pattern `0100 0001` represents the capital letter `A` and the next higher pattern `0100 0010` represents capital `B`.

This is more background than anything else—most of the time (but not all of the time!) you don't need to know the details of what's going on here to carry out data science. However, it is important to have a foundational understanding that when we're working with data in this class, the computer is ultimately dealing with everything as bits and translating combinations of bits into words, pictures, numbers, and other formats that makes sense for humans. This background is also helpful for pointing out that just like the word *data* has connotations related to trustworthiness, it also has connotations of things that are digital and quantitative.

While all of these connotations are reasonable, it's important that we understand their limits. For example, while many people think of *data* as numbers alone, data can also consist of words or stories, colors or sounds, or any type of information that is systematically collected, organized, and analyzed. Some folks might resist that broad definition of data because "words or stories" told by a person don't feel as trustworthy or objective as numbers stored in a computer. 

However, one of the recurring themes of this course is to emphasize that data and data systems are not objective—even when they're digital and quantitative. When I was introducing ASCII a few paragraphs ago, there were two details in there that might have passed you by but that actually have pretty important consequences. First, I noted that ASCII can "encode all the letters of the (English) alphabet"; second, I mentioned that the "A" in ASCII stood for "American." Early computer systems in the United States were built around American English assumptions for what counts as a letter. This makes sense... but it has had consequences!

While most modern computer systems have moved on to more advanced character encoding systems (ones that include Latin letters, Chinese characters, Arabic script, and emoji, for example), there are still some really important computer systems that use limited encoding schemes like ASCII. In 2015, Tovin Lapin wrote a newspaper article about this, noting that:

> Every year in California thousands of parents choose names such as José, André, and Sofía for their children, often honoring the memory of a deceased grandmother, aunt or sibling. On the state-issued birth certificates, though, those names will be spelled incorrectly.
> 
> California, like several other states, prohibits the use of diacritical marks or accents on official documents. That means no tilde (~), no accent grave (`), no umlaut (¨) and certainly no cedilla (¸).
> 
> Although more than a third of the state population is Hispanic, and accents are used in the names of state parks and landmarks, the state bars their use on birth records.

There were attempts in 2014 to change this, but when lawmakers realized it would cost $10 million to update computer systems, things stalled. Moral of the story: even though ASCII is a straightforward technical system built on digital data with no real wiggle room for what means what, it's *still* subjective and biased. How we organize data and data systems matters!

So, even digital and quantitative data (systems) can be biased, which means that we ought to push lightly back against the rhetorical connotations of data as trustworthy. I'm not suggesting we throw data, science, and data science out the window and go with our gut and our opinions, but we shouldn't take for granted that a given dataset doesn't have its own subjectivity. Likewise, we ought to ask ourselves what information needs to become data before it can be trusted—or, more precisely, *whose* information needs to become data before it can be considered as fact and acted upon (Lanius, 2015; Porter, 1996).

### What Is Data Science?

If you think about it, *data science* is somewhat of an unintuitive name. As we noted earlier, *data* are more than numbers: they can be any type of information that is systematically collected, organized, and analyzed. Likewise, *science* simply implies a commitment to systematic methods of observation and experiment.

Given these definitions, *data science* clearly means something more limited than *science* that uses *data*. History, for example, is a commitment to systematic methods of observation and relies on information that is systematically collected, organized, and analyzed, but we (generally) shouldn't expect a historian to describe themselves (or be accepted) as a data scientist. Also relevant here is a critique by data and statistics expert Nate Silver, who once quipped that:

> I think data-scientist is a sexed up term for a statistician (Stats & Data Science Views, 2013)

There's a certain amount of hype, prestige, and even sexiness associated with the term data science, and this ought to encourage us to be critical about how the term is used. Is data science just statistics gussied up to sound cooler? If all scientists use data, who is allowed to have access to the hype, prestige, and sexiness associated with data science?

It is also important to acknowledge the elephant in the server room: the demographics of data science (and related occupations like software engineering and artificial intelligence research) do not represent the population as a whole. According to 2018 data from the US Bureau of Labor Statistics, released in 2018, only 26 percent of those in “computer and mathematical occupations” are women (US Bureau of Labor Statistics, 2019). Across all of those women, only 12 percent are Black or Latinx women, even though Black and Latinx women make up 22.5 percent of the US population. (Women of Color in Computing Collaborative, 2018). A report by the research group AI Now about the diversity crisis in artificial intelligence notes that women comprise only 15 percent of AI research staff at Facebook and 10 percent at Google (Myers, Whittaker, & Crawford, 2019). 

These numbers are probably not a surprise. The more surprising thing is that those numbers are getting worse, not better. According to a research report published by the American Association of University Women in 2015, women computer science graduates in the United States peaked in the mid-1980s at 37 percent, and we have seen a steady decline in the years since then to 26 percent today (Corbett & Hill, 2015). As “data analysts” (low-status number crunchers) have become rebranded as “data scientists” (high status researchers), women are being pushed out in order to make room for more highly valued and more highly compensated men (Fouad, 2014).

Disparities in the higher education pipeline aren't only along gender lines. The same report noted specific underrepresentation for Native American women, multiracial women, White women, and all Black and Latinx people. So is it really a surprise that each day brings a new example of data science being used to disempower and oppress minoritized groups? In 2018, it was revealed that Amazon had been developing an algorithm to screen its first-round job applicants. But because the model had been trained on the resumes of prior applicants, who were predominantly male, it developed an even stronger preference for male applicants. It downgraded resumes with the word women and graduates of women’s colleges. Ultimately, Amazon had to cancel the project (Gershgorn, 2018; Kraus, 2018). 

This example reinforces the work of Safiya Umoja Noble (2018), whose book, *Algorithms of Oppression*, has shown how both gender and racial biases are encoded into some of the most pervasive data-driven systems—including Google search, which boasts over five billion unique web searches per day. Noble describes how, as recently as 2016, comparable searches for “three Black teenagers” and “three White teenagers” turned up wildly different representations of those teens. The former returned mugshots, while the latter returned wholesome stock photography. Unequal representation among data scientists is all the worse for the way it can lead to biases in data science projects.

### What Does "Big Data" Mean?

One possible distinction between data science and statistics is the amount of data we're working with. Technology coverage in the 2010s (and continuing to the present) made it hard to resist the idea that *big data* represents some kind of revolution that has turned the whole world of information and technology topsy-turvy. But is this really true? Does big data change everything?

Business analyst Doug Laney suggested that three characteristics make big data different from what came before: volume, velocity, and variety. *Volume* refers to the sheer amount of data. *Velocity* focuses on how quickly data arrives as well as how quickly those data become "stale." Finally, *variety* reflects the fact that there may be many different kinds of data. Together, these three characteristics are often referred to as the "three Vs" model of big data.

Note, however, that even before the dawn of the computer age we’ve had a variety of data, some of which arrives quite quickly, and that can add up to quite a lot of total storage over time. Think, for example, of the large variety and volume of data that has arrived annually at the Library of Congress since the 1800s! So, it is difficult to tell that big data is fundamentally a brand new thing.

Furthermore, there are some concerns that we should exercise when it comes to big data. For example, when a data set gets to a certain size (into the range of thousands of rows), conventional tests of statistical significance are meaningless, because even the most tiny and trivial results are statistically significant. We'll talk more about statistical significance later in the semester; for the time being, though, it suffices to say that statistical significance is how researchers have traditionally determined whether their results are important or not. If big data makes statistical significance more likely, then researchers who have access to more data will get more important results, whether or not that's actually true in practical terms! Besides that, the quality and suitability of the data matters a lot: More data does not always mean better data.

## The Many Skills of Data Science

Data science owes a lot to statistics and mathematics, so you'd be forgiven for thinking of a data scientist as a statistician in a white lab coat staring fixedly at blinking computer screens filled with scrolling numbers. This isn't quite the case, though: There is much to be accomplished in the world of data science for those of us who are more comfortable working with words, lists, photographs, sounds, and other kinds of information. 

In addition, data science is much more than simply analyzing data. There are many people who enjoy analyzing data and who could happily spend all day looking at histograms and averages, but for those who prefer other activities, data science offers a range of roles and requires a range of skills. Here are some skills that are particularly useful:

* **Learning the application domain**: A data scientist must quickly learn how the data will be used in a particular context.
* **Communicating with data users**: A data scientist must possess strong skills for learning the needs and preferences of users. Translating back and forth between the technical terms of computing and statistics and the vocabulary of the application domain is a critical skill.
* **Seeing the big picture of a complex system**: After developing an understanding of the application domain, a data scientist must imagine how data will move around among all of the relevant systems and people.
* **Knowing how data can be organized**: A data scientist must have a clear understanding about how data can be stored and linked, as well as about "metadata" (data that describes how other data are arranged).
* **Data transformation and analysis**: When data become available for the use of decision makers, a data scientist must know how to transform, summarize, and make inferences from the data. As noted above, being able to communicate the results of analyses to users is also a critical skill here.
* **Visualization and presentation**: Although numbers often have the edge in precision and detail, a good data display (e.g., a bar chart) can often be a more effective means of communicating re- sults to data users.
* **Attention to quality**: No matter how good a set of data may be, there is no such thing as perfect data. A data scientist must know the limitations of the data they work with, know how to quantify its accuracy, and be able to make suggestions for improving the quality of the data in the future.
* **Ethical reasoning**: If data are important enough to collect, they are often important enough to affect people’s lives. A data scientist must understand important ethical issues such as privacy and must be able to communicate the limitations of data to try to prevent misuse of data or analytical results.

While a keen understanding of numbers and mathematics is important, particularly for data analysis, a data scientist also needs to have excellent communication skills, be a great systems thinker, have a good eye for visual displays, and be highly capable of thinking critically about how data will be used to make decisions and affect people’s lives. Of course there are very few people who are good at all of these things, so some of the people interested in data will specialize in one area, while others will become experts in another area. Of course, this also highlights the importance of teamwork.

## Conclusion

We can't possibly cover all these skills in depth this semester, and even these skills are just the tip of the iceberg, which just emphasizes what a wide range is represented here. I hope their importance is clear, though—for example, which of these skills could have anticipated and responded to the problems involved with María showing up as Maria on a California birth certificate?

## References

Corbett, C., & Hill, C. (2015). *Solving the equation: The variables for women's success in engineering and computing*. American Association of University Women.

Fouad, N. A. (2014, August). *Learning in, but getting pushed back (and out)*. Paper presented at the American Psychological Association. https://www.apa.org/news/press/releases/2014/08/pushed-back.pdf

Gershgorn, D. (2018, October 22). Companies are on the hook if their hiring algorithms are biased. *Quartz*. https://qz.com/1427621/companies-are-on-the-hook-if-their-hiring-algorithms-are-biased

Kraus, R. (2018, October 10). Amazon used AI to promote diversity. Too bad it’s plagued with gender bias. *Mashable*. https://mashable.com/article/amazon-sexist-recruiting-algorithm-gender-bias-ai#VSsbMcGmvqqa

Lanius, C. (2015, January 12). Fact check: Your demand for statistical proof is racist. *Cyborgology*. https://thesocietypages.org/cyborgology/2015/01/12/fact-check-your-demand-for-statistical-proof-is-racist/

Lapan, T. (2015, April 11). California birth certificates and accents: O’Connor alright, Ramón and José is not. *The Guardian*. https://www.theguardian.com/us-news/2015/apr/11/california-birth-certifcates-accents-marks

Myers, S. W., Whittaker, M., & Carwford, K. (2019). *Discriminating systems: Gender, race and power in AI*. AI Now Institute. https://ainowinstitute.org/publication/discriminating-systems-gender-race-and-power-in-ai-2

Noble, S. U. (2018). *Algorithms of oppression: How search engines reinforce racism*. NYU Press.

Poovey, M. (1998). *A history of the modern fact: Problems of knowledge in the sciences of wealth and society*. University of Chicago Press.

Porter, T. M. (1996). *Trust in numbers: The pursuit of objectivity in science and public life*. Princeton University Press.

Posner, M., & Klein, L. F. (2017). Editor's introduction: Data as media. *Feminist Media Histories*, *3*(3), 1-8.

Rosenberg, D. (2013). *Data before the fact*. In L. Gitelman (Ed.), "Raw" data is an oxymoron. MIT Press.

Stats & Data Science Views. (2013, August 23). *Nate Silver: What I need from statisticians* [blog post]. https://www.statisticsviews.com/article/nate-silver-what-i-need-from-statisticians/

US Bureau of Labor Statistics (2019). BLS Data Viewer. https://beta.bls.gov/dataViewer/view/timeseries/LNU02070002Q

Women of Color in Computing Collaborative. (2018). *Data brief: Women and girls of color in computing*. https://www.wocincomputing.org/wp-content/uploads/2018/08/WOCinComputingDataBrief.pdf